### ISSUE TITLE
Eway Payment Gateway

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#102]
Has anybody done anything  with  Eway (www.eway.com.au) payment Gateway?  I have a client interested in a store who want to use this for payment. -thanks

**Comment by Mesuva** [comment]
I have, quite some time ago I wrote an eWAY payment method for ecommerce on 5.6.x, using eWAY's Rapid API - it's still in heavy use, I just never put it on the marketplace.

I've not created an eWAY one for Community Store at this point, but it's something I'd personally see as handy due to our Australian clients. eWAY is perhaps a little more complicated than others, but I think it will still be reasonably straightforward as far as payment methods go. 

If you wanted to tackle this yourself, you'd be welcome to use my 5.6 add-on as a reference, the actually processing of the requests is likely to be the same chunks of code.

Alternatively, it might be better to use the ominpay way of doing it, as it appears to be supported: https://github.com/thephpleague/omnipay-eway
I think the Eway_RapidDirect approach would be the one to pick.

As a sidenote, if your client is not tied to eway, they might also want to consider Pin Payments - https://pin.net.au/  Their fees/rates are arguably more competitive for smaller shops. They are sort of my go-to payment gateway in Australia, I've not had any problems setting them up. They also have a virtual terminal kind of thing which can run on a mobile browser.

I've got a community store add-on for Pin payments completed and running on multiple sites now, so if you did go that way I could offer that as well.

**Comment by Mesuva** [comment]
@pvernaglia Did you need to talk about this further, or have you worked something out?

**Comment by pvernaglia** [comment]
Still waiting on the client, so for now no.  thanks

**Comment by Mesuva** [comment]
No worries, was just tidying up some issues and was curious!
