### ISSUE TITLE
Modal add to cart error:  Quantity must be greater than zero

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#112]
When using the Product List block adding to cart from the Quick View modal fails with the error the error 'Quantity must be greater than zero' when the Add to Cart button is not set to be shown.

**Comment by Mesuva** [comment]
I always forget that the Quick view option exists - I was tempted at one point to remove it.
Will look for a fix at some point, shouldn't take long.

**Comment by Mesuva** [comment]
I've had a look into why this is happening. The reason is that modal view of a product is quite detached from the Product List block - in fact at the moment it doesn't know anything about the block it is called for and therefore it doesn't know about the settings it may have.

How would you (or others) feel if we removed this feature from Community Store?

_Personally_ I've never felt the need to use it and I've never really thought it matches with the Elemental styling. I've also thought it's not obvious how to trigger it, with more details better served via an actual button and product page itself.

**Comment by katalysis** [comment]
I have a simple modal working on a project that's about to go live.  The products don't really need a full product page and I fnd for this the modal gives just enough detail.  

To make it work I just moved the hidden field pQuantity outside of the current if else statement.  I've not tested this with product options etc. but it seems to work.

To answer the question I'd like to see the modals retained if possible.

**Comment by Mesuva** [comment]
No worries, I'm pretty sure I have a way to pass through the product list block settings to the modal. 

It just requires a bit of a clean up so that it reflects the settings consistently.

**Comment by Mesuva** [comment]
Fixed by https://github.com/concrete5-community-store/community_store/commit/51e9660f4098dafd458c8affbf3ff3e30e8fb925
