### ISSUE TITLE
Multi-currency option & Premium shipping charge based on address

### ISSUE THREAD

**Issue by paulcurtisnz** [concrete5-community-store/community_store#169]
We're looking at using the Community Store for a relatively simple ecommerce website.  The client is based in New Zealand and will be shipping to New Zealand and Australia.

Shipping charges will be flat rate, but in New Zealand the client wants to be able to charge an additional $2 for rural deliveries (which is standard in NZ). How would we set this up? Rural addresses are identified by RD in the address.

Initially the client will be charging in NZ dollars, but will eventually want to take payments in other currencies. Will this be possible now or in the near future? The payment gateway will be Paypal.

Thanks for any assistance!

**Comment by Mesuva** [comment]
Hi there,

With the shipping, this would be a case of creating a custom shipping method.
There are actually quite straightforward to build, and there's an example shipping method for reference:
https://github.com/concrete5-community-store/community_store_shipping_example

Shipping methods can look at any detail from the cart or order to work out some sort of shipping rate, so this would just be a case of adding into it the check for the RD in the address and adding the extra charge. (Is the letters RD on an address in NZ a standard thing?)

With multi currency, this is something that has actually been discussed quite a few times already, with quite a lot of experienced developers sharing their thoughts. The general consensus is that multi-currency shops are very difficult to maintain and get right.

I think the advice would be to stick to one currency and let the payment gateway handle the currency conversion for you. I personally wouldn't have any issue paying for something in NZD with AUD, as long as I clearly could see that it's NZD being charged. Another point was that there's no harm in adding links to currency convertors or displaying current currency rates, but that it's too complex and problematic to try and do on the fly conversions for display purposes.

So it's not really possible to handle multiple currencies with the store right now and it's unlikely to be added. Either stick to one currency or run two shops (but I appreciate that because it would be the same products in the same language, that's kind of a drag).

Hope that helps!
