### ISSUE TITLE
Call to a member function getPageTemplateID() on a non-object

### ISSUE THREAD

**Issue by recomdesign** [concrete5-community-store/community_store#171]
When i install this mod on my C5 v8.0.3, it gives the following error:
`Call to a member function getPageTemplateID() on a non-object`

When i refresh the page, it says: 
`This extension has already been installed.`

When i open the extension via the Admin menu i end up with the error:
`Invalid argument supplied for foreach()`

```
/concrete/src/Search/ItemList/Database/AttributedItemList.php
     * @param StickyRequest $request
     */
    public function setupAutomaticSorting(StickyRequest $request = null)
    {
        if ($this->enableAutomaticSorting) {
            // First, we check to see if there are any sortable attributes we can add to the
            // auto sort columns.
            if (is_callable(array($this->getAttributeKeyClassName(), 'getList'))) {
                $l = call_user_func(array($this->getAttributeKeyClassName(), 'getList'));
                foreach($l as $ak) {
                    $this->autoSortColumns[] = 'ak_' . $ak->getAttributeKeyHandle();
                }
            }
 
            parent::setupAutomaticSorting();
        }
    }
 
}
```

can you please help me out?

Thanks,

Jeffrey

**Comment by Mesuva** [comment]
I can't replicate any of these errors, I'm able to cleanly install, uninstall and reinstall the package on v8.0.3. I also tried a completely fresh v8 install, no issues there at all. This was with version 1.0.7 of Community Store. 

Is this for a fresh install, or one that you've updated since earlier versions of concrete5? Do you have anything else installed? Could you paste your environment info?

**Comment by recomdesign** [comment]
Hello Mesuva,

Thanks for your quick reply.

My concrete5 8.0.3 installation is basic, i only installed the Migration Tools.
I have attached a .txt file with the environment info.
[environment.txt](https://github.com/concrete5-community-store/community_store/files/700981/environment.txt)

I hope you can find something in the .txt file.

Thank you again.

Jeffrey

**Comment by Mesuva** [comment]
This is quite a strange set of issues, I'm wondering if anyone else is experiencing them.

The only thing I could spot from the environment file is that you're running PHP 5.5.
Although that shouldn't be a problem, if you could change that to PHP 5.6 you may have better luck. 5.5 isn't supported anymore anyway.

**Comment by recomdesign** [comment]
Okay, maybe that is the problem after all.
Within a few weeks, my websites are being migrated to a newer host.
Hopefully it will work after that!

Thank you very much for your help!

Jeffrey

**Comment by recomdesign** [comment]
Hello Mesuva,

I updated the webserver but still experiencing this problem.

Call to a member function getPageTemplateID() on null

I fully uninstalled the addon, and then re-uploaded all files and pressed install.

Kind regards,

Jeffrey

**Comment by Mesuva** [comment]
The 'Call to a member function getPageTemplateID() on null' is caused by the page type for products being removed from concrete5, while the pages themselves are left - but without an associated page type.

Then when you reinstall, the existing product pages aren't put back to the necessary page type, and error when viewed as they simply don't know what page type they are.

Fortunately it's pretty easy to solve, what you do is go to the sitemap, find a product page and select 'Design & Type'. 
![screen shot 2017-02-10 at 8 54 28 am](https://cloud.githubusercontent.com/assets/1079600/22805694/b2ccf3b4-ef6e-11e6-9967-262a58aa7993.png)
![screen shot 2017-02-10 at 8 54 36 am]

Then you'll likely find that there isn't a page type associated with it, it'll be blank in that drop down. Just change it to Product Page and save it. 

That should fix the error, but you'll need to do it to all product pages.

This is one of those nusiances that I think would be nice to solve. Perhaps when the package is installed it can check existing products that are pointing at pages and ensure they are of the correct page type. 

The only time I uninstall the add-on though is during testing. It's very rare that uninstalling and reinstalling an add-on fixes errors.

**Comment by recomdesign** [comment]
Mesuva,

Thank you for the clear explanation.

When i changed the Page Type and opened index.php/dashboard/store i got an error:

Invalid argument supplied for foreach()

I'm running 8.0.3.

Thank you.

Jeffrey

**Comment by recomdesign** [comment]
After i installed the latest Concrete5, everything worked as aspected.

Thank you for your help Mesuva!
