### ISSUE TITLE
Mark as paid throws error

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#172]
In latest version of Store with concrete5 v.8.03, I got this error:

> extract() expects parameter 1 to be array, null given

in

/Applications/MAMP/htdocs/sitename/concrete/attributes/Address/Controller.php, pointing to line 236 after clicking "Mark as paid" of an order that has been placed with all address attributes filled out. 

PS: The error does not occur with concrete5 v.8.0.1 and store v.0.9.9.6 but it will occur with concrete5 v.8.0.2 and store v1.0.1

**Comment by Mesuva** [comment]
I'm not able to replicate this on v8.0.3 and Community Store 1.0.7
I tried both PHP 7 and PHP 5.6, logged in and logged out order placements.

When you say latest version, do you mean the latest release, or the latest from git itself?
I've just pushed up a 1.0.7 release, perhaps try updating to that and seeing if it still occurs.

Otherwise I might need more details to replicate

**Comment by Mesuva** [comment]
I've been able to find this - I believe it's to do when user accounts are created when products are purchased, and then those orders are later marked as paid. 

(normal orders that don't create user accounts can be marked paid without error)

**Comment by cahueya** [comment]
I downloaded directly form Git here, tried both with PHP 5.6 and 7. I now tried with conrete5 v7.5.9 and it works fine with Store v1.0.7 so pretty clear a concrete v8 issue. 

I did the testing with the admin account, so no 'create-on-order' - but I will try investigate further. 

Thank you!

**Comment by cahueya** [comment]
Just for update:
concrete5 v8.0.3, Shop v1.0.7

Pre-Registered User Order -> Error happens

**Comment by Mesuva** [comment]
I'm pretty certain the bug is where:
- If you set a product to create a new user on purchase
- The customer select invoice as the option
- The admin goes in a marks the order as paid (triggering the creation of the new account)

If a customer buys a product that creates a new account, but with an immediate purchase gateway (like Stripe), the new user account is created, the order is paid and the customer is immediately logged in (so no errors).

So there's some small bug in the way that the order complete process is creating a new user account, when it has to fetch the user attributes. Will try to chase it up.

**Comment by Mesuva** [comment]
This should be fixed by https://github.com/concrete5-community-store/community_store/pull/176

(I've tested this, but would appreciate someone double checking it for me)

**Comment by cahueya** [comment]
Just tested this and it works now. Thank you!
