### ISSUE TITLE
Events::dispatch('on_community_store_order', $event);

### ISSUE THREAD

**Issue by edbeeny** [concrete5-community-store/community_store#179]
I used to be able to listen for this event to fire and capture the new generated user.
Has this changed that the new user is created and logged in after this is fired?

If so is this a bug or was it deliberate? 

Thanks

Ed

**Comment by Mesuva** [comment]
I'd say this was a bug/oversight in the (much needed) refactoring that was done to the order complete process.

I've just pushed up a very small change to adjust when the 'on_community_store_payment_complete' event is dispatched: https://github.com/concrete5-community-store/community_store/commit/e73b0c3e20acacfbc9dfe5ef06824242518664b1

If you are wanting to capture new generated users, the 'on_community_store_order' event doesn't guarantee that a new user would have been created at that point (even if it's an order than will create one). The on_community_store_payment_complete event on the other hand is fired after all the post-order processing, so when the user is created. 

The reason it's like this is that you could have an order go through, but on Invoice - users aren't created at that point, they're only created when the order is manually marked as paid. 

So you should be able to just update your code with this small change and change over the event listener to on_community_store_payment_complete instead - it returns the same order object.

**Comment by edbeeny** [comment]
Ryan, 
Perfect thanks, I will have a look tomorrow.

**Comment by edbeeny** [comment]
Ryan,
Whilst that works now, did the code used to log the newly created user in after generation. 
I can't work out now how to capture the user!
Ed

**Comment by Mesuva** [comment]
It should still be logging in the user after they've completed the transaction.
But again keep in mind it's different if it's a transaction the customer has paid for, versus it being marked as paid by the administrator. The later isn't going to log the customer in, but it'll create their account and send them their credentials email.

Calling getCustomerID() on the Order object should return the newly created user's ID, which you can then use to lookup the User/UserInfo object.

So I'd always be looking at the order object to find the related user, rather than trying to find the currently logged in one, because gateways like Paypal, or the Invoice method are going to complete the transaction differently.

**Comment by edbeeny** [comment]
Trying this with Paypal sandbox and paying for the goods which is being recorded as paid. 
It seems the user is not being logged in after the transaction is completed.

**Comment by Mesuva** [comment]
Yes, that's expected, and it's a limitation of the way Paypal handles things.

The transaction complete when Paypal sends a IPN message back to the site. But there's no guarantee that this will happen before the customer returns to the site (and I've found myself that you end up back before the IPN happens). 

If there's a way to handle this situation with Paypal in a way where the user can be logged in when they return I'm not aware of it.

A payment method like Stripe or Authorize.Net that handles the transaction directly doesn't have this problem as it logs you in all in the same request as the transaction itself.
