### ISSUE TITLE
Allows separate customers to pay for same item when stock level = 1

### ISSUE THREAD

**Issue by webiflex** [concrete5-community-store/community_store#194]
**Setting Product1 with stock level = 1 only**
Customer A adds product1 to cart 
Customer B adds product1 to cart
Customer A goes to checkout and pays for product1 via Stripe and completes order
Customer B is still able to move to checkout and pay for product1 also which causes problems for client

Solution perhaps to check stock levels when customer B move to checkout and advise customer B item is no longer available. 

Using version 5.8.1

**Comment by Mesuva** [comment]
I was sure there was a check in the checkout for items in the cart that are no longer available, but I was only partly right in my thinking - the cart only removes items that are no longer available due to them being disabled or deleted

I think this would be fairly easy to add in to getCart function of Cart.php, as that is called every time the cart is initialised (i.e. when moving to the checkout). 

The trickier bit is getting a suitable warning message on screen, but that's less of a concern.

Will try to look at this sooner rather than later.

**Comment by Mesuva** [comment]
I've done a PR for this, would be great if someone could test that out
