### ISSUE TITLE
Reccuring payments/Subscription based product type

### ISSUE THREAD

**Issue by benmlister** [concrete5-community-store/community_store#206]
Had a look in development roadmap and couldn't see subscriptions. Is this something that is possible either as an additional add-on or built into the community store core?
It would be very useful.

**Comment by Mesuva** [comment]
There currently is the ability to create _membership_ style setups, where a product purchase triggers the creation of a new user account, which then can be put into one or more user groups. Then those user groups can have expiry times.. so you can set up paid access sites where you might want to offer time controlled access to certain resources.

But actual recurring payments is actually quite a separate exercise, it requires the definition of the subscription rules and the way transactions are put through is different. You also need ways for customers to manage their subscriptions, update out-of-date cards, put in cancels, or even changing between subscription types.  Then the actual subscription emails notifications, like the ones that say 'Your card is going to expire soon', or even just the recurring invoice don't generally come from the payment system, the store would have to listen for those notifications and handle them.

You also can't just set up subscriptions with any payment gateway, they have to be ones where the card is stored/tokenized on their end for the purpose of repeating a payment. By design, all the transactions community store puts through are immediate ones, where the transaction is authorized by the card details are not actually stored for re-use.

Stripe's subscriptions API is I'd say the go-to option at the moment, but it's not just a matter of adding a few new options in, it's a whole different process to be honest. It would have to be a separate add-on I believe, one with it's own dashboard pages.. in fact it might not even have any connection with community store, as they're just not enough overlap of functionality. 

(that being said, I've spoken to a developer who thinks it is possible to integrate, so something _may_ eventuate)

**Comment by benmlister** [comment]
Thanks Ryan. I knew about store events and user groups having expiry times, which is very useful. I figured it wasn't a straight forward process when different payment gateways have different levels of support for recurring payments out of the box.

Great to know that you're thinking about it.

Ben

**Comment by pvernaglia** [comment]
Hi, Has anyone done any work on reccuring payments?  I have gotten several request recently from people interested in subscription services with Concrete5 web sites. It may be a good feature to have.

**Comment by Mesuva** [comment]
I think my comment above is still applicable to the whole concept.

Reoccurring payment processing is really quite different to the process of completing a single transaction in a typical online shop. If something was to be built I'd actually be thinking it would be it's own completely seperate package, there really isn't much overlap in functionality.
