### ISSUE TITLE
Programmatically adding items to cart, not displayed on initial view

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#211]
I am developing a custom onboarding sequence to add items to the cart programmatically. The first view is a single page (/step1) that adds the items to the cart, and then displays the cart items. Here’s a slightly modified version of the code to add the items to the cart:

// pid is product id, qty is quantity
$products_to_add = '{"data": [{"pid": 8,"qty": 1},{"pid": 9,"qty": 1},{"pid": 10,"qty": 1}]}';
$products = json_decode($products_to_add);

// Add items to cart
foreach ($products->data as $p) {
    $data = array();
    $data['pID'] = $p->pid;
    $data['quantity'] = $p->qty;
    StoreCart::add($data);
}

\Log::addNotice(“Items in cart: “. StoreCart::getTotalItemsInCart());
...
$this->set('cart', StoreCart::getCart());
…

On the initial page load, the cart does not display any items. However, if I refresh the page, it does.

I’ve been trying to determine why no items list on the initial page load. The call to StoreCart::getTotalItemsInCart() returns the correct number of products in the cart. And, if the cart items are added with this code in one view, then redirect to a different page to display the cart, it lists the correct items on every page load.

Any ideas?

**Comment by Mesuva** [comment]
I think this comes down to the way the getCart function looks at self::$cart, to see if it's already set. 
Rightly or wrongly, I think I tried to code this so it wouldn't do a whole bunch of work more than one on a page load, stuff like checking the validity of cart items.

What you could try is changing the getCart function to something like:

 public static function getCart($force = false)
    {
        if (!isset(self::$cart) || $force ) {
.....

Then in your code, change your call to:

$this->set('cart', StoreCart::getCart(true));

This should hopefully get it re-fetch the cart from the session, rather than server up the static class variable $cart.

If that solves it, it'll be trivial to update the master

**Comment by dbuonomo** [comment]
Thanks, that did solve it. Your explanation of the reasoning behind how getCart() was implemented makes sense.

With regard to making this change permanent in master, it seems that this is a parameter that changes the getCart() algorithm, possibly making it difficult to understand what it does in the general case. So, I was thinking I could override getCart() or create a local version of getCart() in my onbarding single page.

Of course, if you think this will be useful in other use cases, it would make sense to add it to master.
