### ISSUE TITLE
Database modifications between releases

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#221]
How best to determine if there are any database changes when pulling updates from master (git pull origin master)? Typically, will all schema changes be isolated to the classes defined in src/CommunityStore that are using the ORM?

**Comment by Mesuva** [comment]
The main indicator should be the package version number. Anytime a code change is made that requires a database update (i.e. a trigger of a package update to rescan the ORM), the package number is incremented. It generally happens when development is happening anyway.

As is convention, the package number incremented anytime a significant bug fix or feature is added in, regardless of database changes. That being said, I'll admit that I sometimes forget this, the most recent fix I did for example didn't include incrementing the package number - I've just done that.

(I'll create a proper release package very soon)

**Comment by dbuonomo** [comment]
Ok, that makes sense. With regard to reviewing specific schema changes, is there an easy way to find those changes? Or, would it pretty much be reviewing the commits and comments on the release?

**Comment by Mesuva** [comment]
I can't think of an obvious way to check what schema changes are made, as it's almost completely handled by changes to the annotations in the individual class files. So yes, reviewing the commits is the way to do this, looking for cases where you see a new /** @Column somewhere.

That being said, the database changes should end up being fairly transparent I would think, handled purely through the update mechanism.
