### ISSUE TITLE
Feature: Country-based pricings 

### ISSUE THREAD

**Issue by moosh74** [concrete5-community-store/community_store#225]
Could be great to have the ability to setup different prices per countries for each products with their own currencies.

e.g
For product XXX, I would like to have : 
- France : 12€
- USA : $20
- UK : £15

Prices displayed in frontend (and prices on checkout) automatically depends with customer ip location, and if logged in, with his shipping address location.

It's something like a multi-shop but easier to implement/undestand I guess.

**Comment by Remo** [comment]
I've done that in the past and I'd strongly advise against this. One price will always be better than the other, perfect to make your customers upset. IP detection also doesn't always work well, especially where I'm from. Maybe others have made different experiences, but I'll not do that again for sure.

**Comment by moosh74** [comment]
For an internatial client, I worked with Mainio on a 5.6 package which worked very well with these features. When you want to sell your product across the world, these features are a requirement, because you have different stock locations, tax locations and so prices/currencies locations.

**Comment by Remo** [comment]
Of course not for a village store ;-) But even for international stores I wouldn't do that. We've just shown currency estimates, never had any complaints with this. I can pay in any currency I want with my credit card, for us it was just an information.

Why would taxes be reflected in the product price? VAT is country specific for sure, but for this you don't change the product price, do you?!

**Comment by moosh74** [comment]
Basically, this was a requirement for 2 of my clients who sell luxury goods in the world. 
And indeed, there is more conversion when visitors pay/view in their currencies.

**Comment by moosh74** [comment]
Imagine you are in USA and see a website who sell product in CHF, do you prefer to buy on a website in $ or in CHF ? 
IMO, in this case, I think twice because I think if I pay in CHF I will pay import fees. while in $, I think stock is in the US.

**Comment by Remo** [comment]
It's exactly what happens if I visit amazon or alibaba... Not having hidden fees is imho a different story, I always hate it if I end up paying a ton for shipping and just get to see that at the end of the checkout process. That applies to stores in the same country as well as overseas and also for import fees, vat, shipping and so on.
But again, I'm just not recommending that as I've made this experience multiple times. If it works for you, great! In the end it probably just matters if anyone is willing to spend time on this.

**Comment by MichaelMaar** [comment]
Just an idea.
There is a add-on for 5.6 (https://www.concrete5.org/marketplace/addons/currency-converter/)

If it still works it would not be that big a problem converting it to 7/8

Just an idea!

**Comment by Mesuva** [comment]
Personally I'm not planning to investigate adding multi currency support, it's just too big and complex for me.

**Comment by moosh74** [comment]
Yes Remo regarding Amawon for example, but they use a domain extension per currency/country.
e.g You can't be delivered to France from amazon.com

But if you have only one domain name/extension and would like to propose different prices based on countries due to your international market to boost your sales ? 

So, how do you handle international prices ? do you sale your product in one unique currency and price ? For my part, I had few clients who would like to set a different fixed price per country/zone and currency to be able to control the exchange rate or because product is a little bit cheaper on USA for example, also to continue with exemple, a visitor located in USA (IP detection - even if it's not very accurate depending the database) can only buy in $ and can only be delivered in USA, same rules for European or UK visitors.

But I know it's a choice, but I find out this very important regarding the brand image.

"Because by obliging your customers to buy in a foreign currency, you discourage them from continuing their purchases by bringing them to the total abandonment of the basket and thus the loss of your sales. According to Statista, 13% of online buyers abandon a site when prices are presented in a foreign currency. Moreover, when a customer makes a purchase in a currency other than his own, his bank charges him a transaction fee; In fact this penalizes your customers who will not want to buy on your online store." (source: https://www.prestashop.com//fr/blog/acceptez-les-paiements-dans-la-devise-de-vos-clients)

**Comment by moosh74** [comment]
Thanks for this debate :)

**Comment by Remo** [comment]
Only partially, there's no amazon.ch, you're being redirect to amazon.de.
If you go there, just make sure you do it right. We failed for a number of reasons:

* What do you do if your customer complains that someone figured out how to use a VPN and now orders their stuff in a different country at a cheaper price? If your shop has a certain size, this will happen.
* Sure, you can just change the available countries and only show the ones matching the location of the IP address.
* What will you do if the IP detection fails? Your customers customer complains that he's living in country A and can't order anything because you don't allow him to select his country. You can suggest to use a VPN, but... well...
* What if it's just about the currency, how will you manage the prices? Automatically? That's what we did and that's where the next problems started. You might have $99 and since you're using some exchange rate service to import the rates on a daily basis, you end up with €90.41 but then the head of marketing shows up and tells you that you can' sell anything with such stupid prices.
* You come up with a magic algorithm and turn it in €89, but then there's a product with a small price and you simply reduce the price by 30% to make the price look nice. And guess what happens next, there's a customer ordering a few thousand of it and your customer can't even cover the profit margin.

I'm very well aware that having one currency has some downsides, but there are two sides and the other isn't really nice and if you want to do this, you have to do it right and consider all those little things, not just those I've listed above.

I guess I wish you good luck and may you not have any of the issues we've had!

**Comment by moosh74** [comment]
- It's not really a problem in the case that you sell in this country... e.g you sell the same product in USA as in France - € price is more advantageous than in $ - if the customer can be delivered in France, great for him. You can do the same with amazon and other ecommerce.

- Yes or use the customer shipping address if logged in. In both case, you can allow all countries and change the total at the end of checkout depending the shipping address. it's normal to pay in the currency of the shipping address ; so if I view $ prices and at checkout I see € prices 'cause of my shipping address, I'm not surprised ; but I agree if you go with multi prices, you need play with it during all the process.

- This happened unfortunately. There are solutions like disabled checkout during debug or switch to default currency with ability to be delivered in all countries (as explained in point 2)

- In my cases, currency are just symbols assigned to a country or zone ; Prices are fixed per country/zone ; So a country can have a specific price and a currency (like prestashop) ; but no automatic exchange rate.

- Yes, that's why I don't recommend automatic rates too. Or just for information but no sales.

I agree with you, but unfortunately, it's complicated to find out the best way to sale internationally for big brands like in luxury industries (jeweleries, watchmakers, ...) where requirements are clear, frozen and who need to touch the most people by maintaining a professional, serious and reassuring brand image.

**Comment by tooqinc** [comment]
Bit late to the discussion here, but I had a client that really wanted to sell in CAD and USD. Given that this was a late requirement change and the first site was already built, I ended up building a dummy site for CAD and having all of the navigation point back to the main site with the exception of the store. On the main site, I simply added a maple leaf icon and a button to purchase in CAD that points to the dummy site. If they click anywhere else, they are viewing the main site again. Stripe maintains a record of both USD and CAD sales for taxes and accounting.

It's not perfect, but it has worked well for them so far. They only sell a handful of products, so inventory management is not too tough for them. A live time currency switcher would be lovely to have, but getting up-to-date exchange rates requires work and/or fees and processing is a different ball of wax.
