### ISSUE TITLE
Missing method in Order class

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#227]
I am attempting to get individual components of a the shipping address for an order (Community Store v1.1.4)

$address1 = $order->getAddressValue('shipping_address', 'address1'));

This throws the following exception:

[Sat May 06 23:00:07.725535 2017] [:error] [pid 13759] [client [redacted]:56546] PHP Fatal error:  Call to undefined method Concrete\\Package\\CommunityStore\\Src\\CommunityStore\\Order\\Order::getValue() in [redacted]/packages/community_store/src/CommunityStore/Order/Order.php on line 1062, referer: http://[redacted]/index.php/dashboard/system/optimization/jobs

It appears that the getValue() method is missing from the Order object.

**Comment by dbuonomo** [comment]
Just found that I could use this method to get the address components:

$order->getAttribute('shipping_address')->address1
$order->getAttribute('shipping_address')->address2
...

Is the intent of getAddressValue() different from the above.

**Comment by Mesuva** [comment]
I does appear that getValue is missing from the Order object. getAddressValue appears to only be used by the shop itself and not at any point on an order object, so I think you've just hit a function that should work for custom purposes, but just was never found to not work.

Perhaps try changing the getAddressValue function in Order.php to:
```
 public function getAddressValue($handle, $valuename) {
        $att = $this->getAttribute($handle);
        return $this->returnAttributeValue($att,$valuename);
    }
```
If you could test to see if that works with your original code that would be handy.
Otherwise your method of fetching the individual address components looks fine - just be aware that I _think_ that only works in v8

**Comment by dbuonomo** [comment]
The change you provided for getAddressValue() worked perfectly.

On a side note, the method I provided in my initial comment does work in v5.7.5.13:

$order->getAttribute('shipping_address')->address1
$order->getAttribute('shipping_address')->address2
...

**Comment by Mesuva** [comment]
That's good to hear, I'll update the master branch shortly, this must have just been an oversight.
