### ISSUE TITLE
Tracking Code?

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#229]
I was about to add this into Community Store for a client when I found some code already in the orders.php single page:

```
$trackingURL = $order->getTrackingURL();
$trackingCode = $order->getTrackingCode();
```

Here's how I hoped to get it working:
1. Order is placed.
2. Website owner enters a tracking code on the order dashboard page
3. Website changes the Fulfillment Status dropdown, it emails the user with an email to say the order has shipped.

I know I can code something up using the community_store_event_example package for 3.

Does CS already have a way to add a tracking code to an order?  There is no field in the order page, do I need to add an attribute with a specific name?

Thanks! :)

**Comment by Mesuva** [comment]
The tracking code is something that was added when I put together the Easypost integration package.
I did consider exposing the tracking code field on the order dashboard page, but I erred against it, as I was thinking that someone who needed to use would be:
- using a custom solution like easypost, where it populates it programmatically
- or, creating some custom shipping process, where they have their own package and dashboard pages, and can handle things however they like

My hesitation with exposing the tracking code was that for something like easypost you don't want to have someone manually editing it, as there is a API process to follow for things like cancellations.

So to answer your question, tracking codes are only programatically added at this point, you're not missing an attribute or anything like that.

If you wanted it in the order dashboard page I'd be happy to review and merge in a PR.

Alternatively, you might prefer to create your own dashboard page, especially since you've mentioned emailing the customer. You could look at the easypost package as a base for that sort of thing since it lists the order, etc.

**Comment by madesimplemedia** [comment]
That makes sense, thanks for the info.
