### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by krebbi** [concrete5-community-store/community_store#24]
php 5.6:
Whoops\Exception\ErrorException thrown with message "Call to a member function getPackageID() on null"

Stacktrace:
#0  in /public/packages/community_store/src/CommunityStore/Payment/Method.php:192

php 7:
Declaration of Concrete\Package\CommunityStore\Src\Attribute\Key\StoreOrderKey::load($akID) should be compatible with Concrete\Core\Attribute\Key\Key::load($akIdentifier, $loadBy = 'akID')

**Comment by Mesuva** [comment]
Sorry about this one, I'd made some last-minute changes to the way payment methods can be configured.

This should be fixed by https://github.com/concrete5-community-store/community_store/commit/84010bbf4a1a58cb0fa9037d6e81afccd128d1a3

Try installing again.

I haven't got PHP7 currently installed, but I've also put in what I think is the fix for the second issue.

**Comment by krebbi** [comment]
thx!

**Comment by Mesuva** [comment]
Let me know if it fixes it and I'll close this issue

**Comment by krebbi** [comment]
5.6 works now. 7 not. but there are more issues with 7 than just installing, as far as I see.

**Comment by Mesuva** [comment]
No worries. I'll close this issue for now - I think PHP7 issues should be raised separately.
(I better get PHP7 installed hey!)
