### ISSUE TITLE
Product Page Variable Issues...

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#241]
OK I'm going to explain this the best I can, it would be easier to show you of course.
This is the primary image for my product:
https://www.mdius.com/application/files/3714/9754/5520/F2_10_00.png

I have made 4 options:
-- Pick Your Connection --
Skived Ends (1 3/4" ROJ & 3/4" Strip)
120 VAC Piggyback Plug
240 VAC Piggyback Plug

They all have different Primary Images.
The primary image for "-- Pick Your Connection --" is:
https://www.mdius.com/application/files/1614/9754/5502/Black_Float.png
Which is the image I want to show up on this page:
https://www.mdius.com/liquid-level-controls/mechanical-floats/standard-floats
Which works fine.

When you click for the Modal window the other pick shows up, which is ok. I just wish I could disable the 
 "-- Pick Your Connection --" like on the Product page. But it does work.

But on the main product page:
https://www.mdius.com/products/10-foot-normally-open-wide-angle-standard

It shows the Primary image for  "-- Pick Your Connection --" which is disabled, so it show the next on the list, which has the:
https://www.mdius.com/application/files/3714/9754/5520/F2_10_00.png
image.

How can I fix this?

Also, do you do custom work on this cart? If so, let me know please.

**Comment by mdius** [comment]
Update, on the Modal window if you add the "-- Pick Your Connection --" it is considered out of stock. Is there a way to disable that like on the products page?

**Comment by Mesuva** [comment]
Sorry for missing this earlier, I'll try to look at this over the weekend

**Comment by mdius** [comment]
OK Thank you, 1 more thing too. It is related to this issue.
https://www.mdius.com/pumps/basin-packages
The SKU for this product should be:
Custom Dual Pump Basin
But instead it shows the SKU for the first option I have set up.

Also, let me know about the custom work too please.

**Comment by Mesuva** [comment]
Sorry for the delay Joseph

Can I ask what version of community store you are running here?
There's been a fair bit of work/fixes on the way variables are handled, I'm wondering if some of the more recent work fixes your second issue.

You might find it useful to test out on a copy of your site an update to this version here:
https://github.com/concrete5-community-store/community_store/tree/develop
If that fixes things it'll just be a case of updating your site as soon as we're comfortable that it stable enough to merge into master and put out as a release.

With the modal, this often lacks behind the functionality of the main product display simply because I never think to check it (I'll admit that I personally don't like the modal and which it wasn't there, but I know people use it).  It could be some time before I have the chance to look at it again, my main focus is testing out the most recent merges/fixes and ensuring that it all works on 8.2

Is the modal a critical part of your project, or can simply turn it off until it's fixed?

**Comment by mdius** [comment]
My version, I believe is the latest. I install this a bit over a month ago, then I added the VAT update a little over a week after you added it.
`$pkgVersion = '1.1.6.1';`
Then lets not worry about the Modal window. It works and that is good, may not be perfect, but I'm OK with that.

How would I go about installing the updates? Should I wait till they are fully released? When I did the update to the 1.1.6.1 you had a nice run down of each effected file and the changes, I assume that will be the case once the new version is released?

Also, are you possibly planning on adding a way to give discounts on higher quantities? Like 1-9 $5, 10-25 $4.50?

**Comment by Mesuva** [comment]
Hi Joseph, with updates it's really just a case of taking a backup of your site, replacing the community_store folder in the packages folder with a new one and then triggering the upgrade within the extend concrete5 section of the dashboard. You shouldn't need to manually make edits.

I would wait for the next 'release' before upgrading - the develop branch has quite a lot of new stuff in it and I'm currently testing and trying to fix issues with attributes on 8.2. I have a project I'd like to apply these updates to myself so I should have a new release out soon.

With the tiered discounting, I personally don't have a plan to add this feature in myself, I've never had a client ask for it. It's been asked for here on github before, but it's not a trivial thing to add in due to the way variations and options work. I would need a business case to invest the time into that feature ahead of some of the other features I know the store should have.
