### ISSUE TITLE
Hitting max execution time updating products - C5 v8

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#252]
It is fast to add/update products until you add a few options, then it becomes very slow and reaches max-execution time.  I am using PHP7, Concrete5 v8.1. 

Please see error attached.
![comm_store_max_exec](https://user-images.githubusercontent.com/10834004/28246734-b46c17b6-6a18-11e7-8ff1-479dfc03f1a9.jpg)

Fortunately, it does actually save the product, but adding options is very slow/times out.  I am adding 5 option types, one has 27 values, the others have between 2 and 8 values each.

**Comment by Mesuva** [comment]
I've just a pull request to make this process more efficient, you might like to try that.

However this may come down to how you are using the options - if you have them all set to Yes for 'In Variations', then they'll be included in the variations combos and it might simply be exploding in number.

<img width="795" alt="screen shot 2017-07-16 at 10 45 22 pm" src="https://user-images.githubusercontent.com/1079600/28247864-af272128-6a78-11e7-8619-c3eb46dfd5c7.png">
This has only recently been added, previously it was effectively always set to yes. If you haven't got that option, try updating to the latest release, and then applying my PR changes.

In the pull request I've put in a limit of 50 variations, that's at the point where saving and duplicating products is still reasonable to me. At something like 100 it times out on my fast machine.

**Comment by madesimplemedia** [comment]
Thanks for this.  
I need to pull the latest version, but what exactly does that "In Variations" dropdown do?  I do need all options to be independent of eachother.

**Comment by Mesuva** [comment]
The drop down selects whether the particular product option is considered in the product variations, in other words, will that option affect the product's price, image, weight etc.

Just say you have two options
Color - Red, Green, Blue
Size - Large Small

If you have them both with In Variations set to yes, you'll end up with _6_ variations
Red Large, Red Small, Green Large, Green Small, Blue Large, Blue Small

So just say you want to just change the price based on the size, you would set the In Variations option for the colors option to no. That takes that option out of the combinations it will create for the variations.

The issue is that if you have two or more long lists of options in variations, everything multiplies, so you can end up with an enormous number of variations. You may however want something like the six combinations, every configuration, you can still do that.

This new option is only relevant when you have 'Options have different prices, SKUs or stock levels' ticked.

**Comment by madesimplemedia** [comment]
Thanks for explaining that, yes I can now see the issue.
I need to do that latest pull and we'll see how it goes.

**Comment by madesimplemedia** [comment]
I made the changes from your latest commits but I don't get the "in Variations" select box?

**Comment by Mesuva** [comment]
It should look like this:
![screen shot 2017-07-26 at 7 43 41 am](https://user-images.githubusercontent.com/1079600/28596120-3d7ce52a-71d6-11e7-9050-0f4e5e38e2b5.png)
Keep in mind that it only appears for the Option List type of option.

**Comment by madesimplemedia** [comment]
I've got it now, issue was with me, thanks! :)

**Comment by madesimplemedia** [comment]
Sorry me again.  I need to increase the max variations now.  Only by say 50% to account for my options, how do I do this?

**Comment by Mesuva** [comment]
This should be the line of code that controls the limit of variation combos.
https://github.com/concrete5-community-store/community_store/pull/253/files#diff-b685cdfbcba7246563dc19da64cb8bd9R631

You could try 100 and see how that performs

**Comment by madesimplemedia** [comment]
Many thanks, that is working nicely at 100 and it only takes a few seconds to save.
