### ISSUE TITLE
Need "Option" to allow customer to upload files

### ISSUE THREAD

**Issue by barkingtuna** [concrete5-community-store/community_store#255]
Unless I've just missed it, it'd be helpful to add "image/file upload" as an options under the "Options" tab. I'm building a custom cowboy boot website and the client needs ability for stones to upload logos and artwork specific to the product they are purchasing.

**Comment by barkingtuna** [comment]
Temporary workaround was to create a hidden form and drop a link in the receipt email

**Comment by Mesuva** [comment]
I think there's a lot of complexity to allowing a customer to upload files, so much so that I was going to suggest handling it after the order somehow - via email, a form, etc. A form pages then gives you the opportunity to outline file requirements - asking someone to put in a order number to help match it up isn't horrible in my opinion. This could potentially be a single page so you apply custom validation and processing.

The order complete page should have an editable area on it, so you could also add in the link to the form from that point as well.

If files are uploaded as part of adding to the cart, you then have to:
- consider where the files go to, how big they can be, filtering to file types
- adjust the javascript to handle the upload - this would be pretty tricky
- adjust the cart to show that a file has been uploaded with adding to the cart
- handle cleanup of files if they remove from cart (or even after processing)
- adjust the order details to show links to these files

That feels very messy and something I think would really require a custom ordering system to handle that way.

Personally I'm not sure if I'd be happy with the public being able to directly upload files that end up in the site's file manager, especially if they aren't actually paying customers yet.
