### ISSUE TITLE
Omnipay integration

### ISSUE THREAD

**Issue by Remo** [concrete5-community-store/community_store#27]
I'm a fan of omnipay as it requires just one implementation and gets you a ton of different payment gateways: https://github.com/thephpleague/omnipay

Any reason not to use that? Would certainly look good if there was support for 25 different gateways!

**Comment by Mesuva** [comment]
Yes, Omnipay is great, I've used it for https://github.com/concrete5-community-store/community_store_stripe  (as well as another payment gateway I haven't uploaded at this stage).

What Omnipay does is handle the server side processing of payments with a consistent API, but what it _doesn't_ do is handle all the different ways tokens need to be generated on the client side. Each gateway has their own client side script that needs to be included, with different javascript processes. So there's not really the possibility of just dropping in Omnipay and supporting a whole bunch of gateways instantly, the work has to be done on the credit card form side for each gateway.

I also make it a policy that I only use gateways that do token based payments - I never utilise ones where the credit card details are passed through the webserver. 

The Omnipay/common library _was_ originally included with the core Store as it initially appeared logical to include a library once that multiple gateways would use. However, you still have to install each individual gateway's ominipay library (e.g. https://github.com/thephpleague/omnipay-stripe), which is going to be through a separate package. 

What I found is that ominpay/common is set as a dependancy when using composer to install an individual gateway library. So if composer is used to create individual payment methods, it'll pull in omnipay/common anyway. I couldn't find a way with composer to say 'when you pull in this composer package, don't pull it one of it's dependancies as we already have it'.

Generally you tend to set up shops with only a few payment methods active, normally one credit card option, so realistically the omnipay library is only going to be included once anyway.

The other side of it too is that you might set up a shop with just invoice ordering, or some payment gateway that isn't in ominpay - no point including a large library just in case it might be used.

**Comment by Remo** [comment]
> What I found is that ominpay/common is set as a dependancy when using composer to install an individual gateway library. So if composer is used to create individual payment methods, it'll pull in omnipay/common anyway. I couldn't find a way with composer to say 'when you pull in this composer package, don't pull it one of it's dependancies as we already have it'.

That's the main problem I see at the moment. To me the `composer.json` is placed completely wrong in concrete5. It should always be in the root so that we get one directory called `vendor` in the root and not in each package and the core.

> Generally you tend to set up shops with only a few payment methods active, normally one credit card option, so realistically the omnipay library is only going to be included once anyway.

We often started with PayPal since it was cheap on the initial costs, but added another "proper" credit card gateway since PayPal seems to scare of a lot of customers in Switzerland. Having two libraries with omnipay in it would probably be fairly common over here.

> The other side of it too is that you might set up a shop with just invoice ordering, or some payment gateway that isn't in ominpay - no point including a large library just in case it might be used.

I would agree if we could nicely add the common package for multiple payment methods, but since this isn't easy, I'm not so sure about. At the end we have a ton of libraries and code in concrete5 which most people don't use. I guess you hardly ever use every function there is, whether's it's about a CMS, an operating system, an IDE and so on..

**Comment by Mesuva** [comment]
I agree with your thoughts on how there really should be one vendor directory at the root - that's really how composer is intended to be used. Composer really isn't suited to systems with a plugin architecture, it's more for managing the requirements of a single application.

So the same sort of thinking applies for ominipay, it's really intended for being able to easily add payment support to a custom project. In that case it works great, but for concrete5 it starts to get messy with the multiple vendor folders - that's not really how composer is intended to be used.

Because concrete5 and packages aren't really using composer as designed, I don't know if there is a correct answer for this. 

At the moment it appears that having multiple gateways installed that include omnipay common doesn't appear to break anything, but I think that's really only when the libraries pulled in are the same.  On the flip side, if we have ominpay in the core we can't use composer to build individual gateways. 

The conflict in how this all fits together is really because of concrete5's plugin style architecture. 
A 'solution' to the problem above is to actually just create one add-on to handle all your gateways together that you need at the same time. It's actually not hard to do this as the structure of gateways to extend the store would support this, it would just be a bit of copying and renaming... but then this would have to be handled by a developer every time they wanted to add further gateways. That loses the whole add-on advantage!

Beyond the advantage of being able to use composer to build gateways add-ons, not having omnipay common in the core is that we now have this package not require composer at all. I recently do a commit where I removed some code that used the last composer dependancy. So right now composer isn't needed for the core store - I see that as a bit of a plus.

**Comment by Remo** [comment]
Or we just build a "concrete5-omnipay-common" package and a package for each gateway with a dependency on "concrete5-omnipay-common"?

**Comment by Mesuva** [comment]
I did think of that, but then I think we'd hit the original problem of not being able to use composer to build the individual packages - each would still try to pull in omnipay common.  

Or... maybe it's a case of having an concrete5-omnipay-common, and each payment method having it automatically switch on and off it's vendor directory if it's installed... if you don't have omnipay common installed it uses it's own copy.

~head explodes~

**Comment by Remo** [comment]
Whatever we can or will do, it's going to be a bit silly. The only thing that would fix this, is to change the core and that doesn't seem to happen anytime soon..
