### ISSUE TITLE
Skipping Order Number

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#278]
Hi,

I have noticed that sometimes there is a skipped order number, for example:
71
72
74

What happened to order 73?  Is it one that was abandonded at a certain stage?

Thanks
Dave

**Comment by Mesuva** [comment]
If you are using a gateway like Paypal, what happens is that when a customer confirms an order and leaves the site and heads to Paypal to pay, it's at that point than an order needs to be locked in place, including the order ID. If they then decide not to pay, that order never gets marked as completed. That then explains the gaps in order numbers.  

eCommerce for 5.6 solved this by allocated order numbers after payment, which then didn't necessarily match the database ID of an order. I did consider this, but didn't think it was worth adding that extra level of complexity just so that there aren't gaps.
