### ISSUE TITLE
No longer Generating Product Pages...

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#281]
Community Store v.1.2
Worked great Friday, Monday I try to add products and I get "HTTP 500 error".

I've rebooted my server and cleared cache. No luck.

**Comment by AdamBassett** [comment]
Check your logs.  Something changed on the server.  500 usually is caused by permissions but can be any number of things.  The server logs should tell you what happened that caused the 500 error.

**Comment by mdius** [comment]
I searched for the logs and I found nothing.  I found logs, but none that say anything about the 500 error. I also can add a page using the normal Concrete system. Just not through the shop.

**Comment by AdamBassett** [comment]
Are you looking in your server logs?  Don't look in C5 that's a server error, not a C5 error.

**Comment by mdius** [comment]
Yes I am, also having someone from the server help me look for it, they cannot find a 500 error.

**Comment by mdius** [comment]
There are no 500 errors on my servers logs.

**Comment by AdamBassett** [comment]
The logs may not say 500 specifically, they are generally more specific.  Your looking for something like permissions denied or something about a module not being loaded.  You want to look in the logs for the web server i.e Apache or Ngenx and the syslogs.  Make the call and note the time then search the logs for any entreaties in the log at that time.  There is an error being thrown and the web server spits out a general 500 because it is not told what the error is for security.

**Comment by mdius** [comment]
`ModSecurity: Warning. Matched phrase "../" at REQUEST_URI. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "34"] [id "930110"] [rev "1"] [msg "Path Traversal Attack (/../)"] [data "Matched Data: ../ found within REQUEST_URI: /shop/cart.php?a=test&templatefile=../../../../../../../../../etc/passwd\\x00"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "7"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "OWASP_CRS/WEB_ATTACK/DIR_TRAVERSAL"] [hostname "mdi.mdius.com"] [uri "/shop/cart.php"] [unique_id "WX4x1aQBOOddUOiH58Z7ZQAAAMs"] `

Could this be it? It is the only thing the server support found. I cannot find the syslog at all, but I've looked through all the Apache logs.

**Comment by AdamBassett** [comment]
Maybe but probably not its a warning not a error.

**Comment by AdamBassett** [comment]
If its a permissions error it would look something like this. (13)Permission denied: httpd: could not open error log file /home/test/apache/domain1.com/logs/error.log.
Unable to open logs

**Comment by AdamBassett** [comment]
Looking at that a little closer it dose say [severity "CRITICAL"] it might be the thing causing the issue it looks like it does not like something in the request.  It looks like it thinks your trying a Path Traversal Attack.  I would look deeper into this and see why ModSecurity is throwing that warning.

**Comment by mdius** [comment]
I just cannot find anything else. I have no idea where to look for an other logs.

I have no idea how to see why ModSecuirty is throwing that warning.

But I do thank you for all your help.

**Comment by AdamBassett** [comment]
Mod Security is trowing that warning because the url for some reason contains ../ in it.

**Comment by mdius** [comment]
The /shop/chart.php is confusing me. There is no /shop/ anyplace. It was my old URL.

**Comment by AdamBassett** [comment]
If that is not a C5 call then that error is not related.

I don't know your hosting environment and this is an issue with the host not C5.  Something on the host changed, if you have made no edits to the code.  If there is a chance someone made a code change then I would look into that.

Have you tried installing a fresh copy from scratch for testing?  Do you get the same behavior on the same host with a different install?  If the test install works then what is different in the settings?  If it does not I would be talking to my host about what changes they made to the server.

Other than that advise I'm not sure what else anyone here can help you with since it appears to be a host issue.

**Comment by mdius** [comment]
I have a backup server to test things on, I'll have to get this set up tomorrow to use. I'll post how that goes.

**Comment by Mesuva** [comment]
I would try to trigger the 500 error and then ask your host to check the Mod Security logs again. Normally mod sec blocks throw 403 or 404 errors, but there's a chance here that mod security has been updated with new rules on the server and doesn't like something about the product save request

I'd also look at your .htaccess file to check if anything has changed there, like the PHP version.

**Comment by mdius** [comment]
I did trigger the 500 error when I was talking to them. But the code I added seemed to be from something else that does not exist anymore. I switched my php version to 7.0 from 5.6 to test it and it caused the same error, so I changed it back and still the same thing.

I checked my .htaccess file and nothing changed in this either. I'm still working on the backup site.

**Comment by mdius** [comment]
Well, this is interesting. I solved this issue.

Product Name:
High Temp Float Switch - 10 Foot - 225°F/107°C - Normally Open - Intermediate Angle

The issue is the ° sign. I removed those and it worked flawlessly.

**Comment by Mesuva** [comment]
The filtering of characters when pages are created should be handled by concrete5's own code, but I could wrong about that, maybe a page title needs some further filtering before being used in the API call.   What happens when you try to create a page with the degrees symbol in the page name normally?

**Comment by mdius** [comment]
Well I usually use the `&deg;` statement, but it converts it to the raw character in Concrete, so it looks like an ALT+0176 ( ° ). So I assume it is just trying to put the ° in the URL and crashing.
