### ISSUE TITLE
Error when adding product list with the Best Seller option

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#285]
`Doctrine \ DBAL \ Exception \ NonUniqueFieldNameException
HELP
An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID WHERE (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID ORDER BY pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC, pID = ? DESC' with params [99, 98, 66, 22, 60, 15, 123, 4, 72, 127, 52, 100, 247, 329, 3, 243, 59, 136]: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'pID' in order clause is ambiguous`

I am just trying to add a product list with sort option "Best Sellers". It used to work, so it must have messed up when I did an upgrade.

If need be I can put on full debug mode and give you a link to the error. Also, why is the option:
Related Products Order
Always unselectable?

**Comment by Mesuva** [comment]
Try this change here:
https://github.com/concrete5-community-store/community_store/commit/2677facc3f01228e45e357250a7f55cd7bb219d1#diff-82f99f6e29e208e07ba4979e54841732R185

(other javascript stuff in the same commit isn't relevant)

**Comment by mdius** [comment]
`Doctrine \ DBAL \ Exception \ InvalidFieldNameException
HELP
An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID WHERE (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID ORDER BY p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC' with params [99, 98, 66, 22, 60, 15, 123, 72, 4, 127, 52, 136, 247, 100, 329, 243, 59, 3, 251]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p.ID' in 'order clause'`

Tonight I'll leave the debug mode on  so you can see the full error report.

https://www.mdius.com/test5

**Comment by Mesuva** [comment]
Check the change you made, it's p.pID, not p.ID.

On 3 Oct. 2017 1:56 am, "Joseph Snedaker" <notifications@github.com> wrote:

Doctrine \ DBAL \ Exception \ InvalidFieldNameException HELP An exception
occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p LEFT
JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID
WHERE (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID ORDER BY
p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC,
p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC,
p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC,
p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC, p.ID = ? DESC' with params
[99, 98, 66, 22, 60, 15, 123, 72, 4, 127, 52, 136, 247, 100, 329, 243, 59,
3, 251]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p.ID' in
'order clause'

Tonight I'll leave the debug mode on so you can see the full error report.

https://www.mdius.com/test5

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/concrete5-community-store/community_store/issues/285#issuecomment-333569238>,
or mute the thread

**Comment by mdius** [comment]
Check the change you made, it's p.pID, not p.ID

Yup!
That fixed it! Thank you again.
