### ISSUE TITLE
Database error after processing order

### ISSUE THREAD

**Issue by snapdesign** [concrete5-community-store/community_store#287]
Hi. I thought everything was working great on this plugin but I'm getting an error (see attached) after it processes the order via PayPal. The order goes through but then when browsing back to the shop/products page, it is broken with the attached message. I'm not a developer so doesn't mean much to me but posting up so someone might be able to fix the bug. 
I'm running Concrete 5.7.5.13 from the updates folder (would this make a difference?).
Apart from the error, it's looking like a fantastic product! I guess I shouldn't have tried using it on a live site yet :(

Thanks,
Nev
![community-store-error](https://user-images.githubusercontent.com/32467199/31096531-3bec2f22-a7b4-11e7-9113-2755df6a65d3.jpg)

**Comment by Mesuva** [comment]
I think you might have hit the same issue as this one here, https://github.com/concrete5-community-store/community_store/issues/285, where a product list is displaying in 'Best Sellers' order.

Fortunately the fix is easy, it's just changing this line here:
https://github.com/concrete5-community-store/community_store/commit/2677facc3f01228e45e357250a7f55cd7bb219d1#diff-82f99f6e29e208e07ba4979e54841732R185

**Comment by mnakalay** [comment]
@Mesuva, I'm not a sql guru but isn't it weird that we're trying to assign a value to pID in an ORDER BY clause?
Why would it be ORDER pID = ? instead of just ORDER BY pID

Also it probably should be p.pID

**Comment by snapdesign** [comment]
Excellent! The fix worked. Thanks guys.
