### ISSUE TITLE
No Shipping Options Available To Customers Using IE

### ISSUE THREAD

**Issue by tooqinc** [concrete5-community-store/community_store#291]
CS Version v1.2.1
IE Version v113193.14393.0

During checkout, users using the IE browser are not presented with any shipping options which leaves them with now way to checkout. Process works in current versions of FF, Chrome, Edge, and Safari. Appears to be limited to IE.

I can't say for sure if this is happening in newer versions of CS as I don't have time to install and test updates for my client. If someone can also check their install, that would be helpful.

Will work on the issue as time permits, but happy to see if someone else can get to it first.

**Comment by Mesuva** [comment]
Can you check the Developer Console in IE and screenshot any errors there?

I found that in IE11, but not in Edge, I was getting some errors with the Pin Payments payment gateway. What payment gateway have you got in play?

The problem was that this line:
_$(function() {_     
which is the same as 
_$(document).ready(function() {_

is initiating stuff to do with the payment gateway, before the browser has been able to fetch the related script. I think newer browsers will fetch the script first, whereas IE11 and below doesn't.

Replacing that call with something that waits for the page, instead of the DOM being ready appears to fix it, so:
_$(window).load(function(){_

**Comment by mnakalay** [comment]
@Mesuva, I didn't check with IE11 however, in your CommunityStoreFunctions.js you have the function

`function updateActiveTab(historyPopEvent = false) {`

And IE11 pukes when you give a function parameter a default value.
I know because it just happened to me on a different project.

The recommended way to do it for IE11 is this one

```
function updateActiveTab(historyPopEvent) {
historyPopEvent = historyPopEvent || false;
```

And I checked all the JS files, it's the only function you have with a parameter with a default value

**Comment by Mesuva** [comment]
I did actually resolve this (or at least the bug that I found). It was to do with some of the payment gateways and the way that it was loading in the scripts.

Here's an example:
https://github.com/concrete5-community-store/community_store_stripe/commit/1f302104cc457e9015bbe52b0b752a7a4a1fdb7d

But I agree that that default value in the updateActiveTab function should be fixed
