### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by edsaxmoore** [concrete5-community-store/community_store#322]
I've been able to successfully make a purchase with Stripe. However, once the purchase is made and it goes back to the site, I get the following error: Call to undefined method Concrete\Package\CommunityStoreStripe\Src\CommunityStore\Payment\Methods\CommunityStoreStripe\CommunityStoreStripePaymentMethod::sendReceipt()

Thoughts?

Thanks!

**Comment by Mesuva** [comment]
Do you have the function sendReceipt on your CommunityStore/Payment/Method.php file?
https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Payment/Method.php#L283

What version of community store are you running?

I'm not hitting this error myself, as although sendReceipt doesn't exist within the Stripe class, because that class extends CommunityStore/Payment/Method the method should exist as a default state. Looking at it with fresh eyes I actually think it should be defined as a static function, but it should still work.

**Comment by edsaxmoore** [comment]
I just reinstalled the version 1.3.1 and it works now. It was exactly as you showed in the link. Thanks for your help! Very nice store.
