### ISSUE TITLE
Select Attribute in order page not showing result after product purchase and in mail

### ISSUE THREAD

**Issue by ghost** [concrete5-community-store/community_store#346]
Given a Select attribute in order attribute but the result value is not showing in the product order page or in mail.

**Comment by rosie607** [comment]
If my understanding is correct attributes aren't output anywhere by detault. 
You can assign them in the dashboard then you need to access them programatically by adding them to your own product or product list template for instance like this:
`$myAttribute = $product->getAttribute('my_attribute');`
`echo $myAttribute;`

Options are shown on a product without you having to do anything so might be worth seeing if you could use those for your needs.

**Comment by Mesuva** [comment]
@rosie607 You're correct in your description in terms of _product_ attributes, but order attributes that are added to the checkout should then show automatically on emails and in the dashboard.

I thought that this problem had been addressed, but maybe that was just with checkboxes.. what community store version are you running @Arunsolu ?

**Comment by Arunsolu** [comment]
@Mesuva Sorry for the late reply. I am Using the latest version of community store.
The issue is i had is i had give select attribute in dashboard in the order attribute which is display in the checkout page. Till the completing of the product it show the selected numerical value but after completion the order. In order page the value of the select attribute is not showning and in the mail that we receive the select attribute value is not showning. All the other attribute that i add is showning in the order page and mail but not select attribute...  Is it because the attribute value it is not saving in the database table 'atselectoptionsselected'. ?
