### ISSUE TITLE
Add option for control cart totals from outside the CS

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#353]
Hi,

One of my client want to modify the cart total from some other package, i edited this file :
`community_store/src/CommunityStore/Utilities/Calculator.php` for implementing it.

now i have done a new adjustment on the above file, please check it
https://github.com/midhun1993/community_store/commit/b0f3011ebe49f0b18ac1766fbd7a7d5be272ddb9

line 201 will be this
`$newTotal = $total ;`

if it is helpful then i can give you a pull request.

thanks 
midhun

**Comment by Mesuva** [comment]
I like the concept of being able to control the cart in different ways, but the bit that concerns me is how the changed value isn't accounted for in a line item.

The individual line items, with any shipping and then the discounts should always add up to the cart total - otherwise it just appears when reviewing an order that it's miscalculated.
