### ISSUE TITLE
Product List Block doesn't show original price for discount rules

### ISSUE THREAD

**Issue by Ta2Ta2** [concrete5-community-store/community_store#358]
Hi,

After enabling a % discount rule, the product list block shows only the discounted price only. Unlike when applying sale price to the product where it shows original and discounted price.

I believe when enabling % discount rule, the original price should be visible next to the discounted price.

**Comment by Mesuva** [comment]
I'm in two minds about this. A discount doesn't necessarily have to be due to a promotion or sale, it could be due to something like a membership discount. In those cases, you may or may not want to actually bring attention to the original price at all, or you might have different sets of users with different discount amounts. The product list block showing the discounted rate was intentional.

But I also understand there are going to be times where you want to do '20% of storewide this weekend', and directly show the specific discounts involved, and in those cases it's not practical to review every product and set a sale price.

Will give it some thought

**Comment by Ta2Ta2** [comment]
It's always nice to show before and after price... kinda of making end user motivated to buy..just saying

**Comment by AdamBassett** [comment]
I disagree, there are some use cases where the original price should not be shown.  I have a few clients where this was specifically requested.  In these cases the discount is different for each member, and they don't have public pricing. Showing the base price in this case would be a bad idea since they don't sell to guests, you have to be a member. They negotiate the price based on a % of their base price, but their members have no idea what that base price is and they don't want them to know.  All their members know is that they are getting the contracted price.

I would say that it might be nice to have a toggle in the discount to pick one way or the other, but I'm not sure if there is enough use case to warrant the time to add this function.  I have never looked at the code on how this is done, but you might want to look into customizing the block code or something to make it do what you want.

**Comment by Ta2Ta2** [comment]
Haven’t heard of your particular used case. If we look at majority of global online stores you will find my used case all over the place. Your client has his own strategy so do everybody else. 

That being said , Customizing the block code or adding the toggle option is the way to go I would say.

**Comment by mdius** [comment]
I was able to show discounts with the original price on any discount.
www.mytinytown.com My test site. (Sorry the site is a little slow)
Check featured items on the main page at the bottom.
Add anything to the cart
Use code 50Off
Then check things out, see the discount now show everyplace (check the featured section again). If you want to complete an order you can, it uses invoice as a payment option, and again it is my test site. That way you can see that is shows the discount through the full process.
