### ISSUE TITLE
Update Fulfilment Status Notifications

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#363]
I was wondering how difficult it would be to have a pop up stating something like, "email customer of status change?", it would be even better if it could include a filed to put in a UPS tacking # on Update Fulfilment Status changes.

**Comment by Mesuva** [comment]
The mechanism isn't so hard, it's deciding on the format of the emails and providing a way to configure those.

There is an 'on_community_store_order_status_update' event that gets fired.
It's potentially the job of an add-on to respond to those events and trigger some sort of action.
On the other hand, it might make sense to just include in the core, since it's a pretty common thing to be able to want to do.
