### ISSUE TITLE
Feature request - separate store core to allow adding rental functionality

### ISSUE THREAD

**Issue by linuxoid** [concrete5-community-store/community_store#371]
Is it possible to separate the Store core (orders, attributes, reporting etc.) from products (shipment etc.) as such so that other types of stores could be developed based on the same core code base, such as rentals? E.g. car rental, property rental, tools rental etc? Let the user select what type of store they want to create: products, digital, rental etc.

It would be an overkill to start from scratch "reinventing the wheel" especially if there's already such a great core functionality.

**Comment by Mesuva** [comment]
Probably not, I'd say there'd just be too many aspects to products that get referred to by the checkout and ordering process. While it's always good to try and not tightly-couple components, and I'm sure there are many places in community store where the way entities interact couple be improved (interfaces, decorator patterns, that kind of thing), ultimately a shop still needs to represent the _thing_ being purchased somehow, with a name and a price. Pretty hard to seperate things at this point.

I'd be approaching it by adding settings to be able to hide certain features/fields, rather than trying to rip whole sections out and replacing them. Or maybe working out a way to override or extend the Product object. The Product object in the system doesn't really make any assumptions as to what kind of thing you are selling - you can use the same thing to sell physical items, digital items or for things like tickets to an event. 

If I was looking to do rental for example, I'd be coding up some side package that allowed me to manage whatever I'm renting, I'd be completely free to build that interface how I saw fit, including adding all the specifics for the problem domain. Car rental is going to be different from property rental for example, in that you might rent cars for half days, or depending on the pickup time.

Then on the community store side of things I'd probably create one 'Rental' product, setting that to allow entry of a custom price and a text field.  Then on my front end I'd be modifying things so it really offers a list of rental items (depending on availability, etc), where it's using the same product but different input prices and option text.  You might right a single page function to accept a product ID and a rental item ID and it does the job of adding them to the cart correctly.

Then on checkout, on the on_community_store_order event I'd do whatever updating I needed to do, to manage the availability of that rental item.

I did something similar to this back in 5.6.x days with eCommerce, where a client wanted to sell photos. We didn't create a product for every photo, we just created a product for every size/canvas they could order and we adjusted a gallery block to include add to cart controls. Adding the cart was really just adding the size selected along with a code for the image selected.

I think there'd just be a lot of value in being able to use a vanilla community store add-on to power things, so you don't have to continue to maintain that codebase with fixes or newer features.
I'd be exhausting all the ways I could build something on the side, ways to add products to the cart in certain ways and provide restrictions, before trying to remove and replace the products aspects in community store.

If there were aspects in community store that you think would make things a lot easier, things like new events or ways to customise the product management I'd certainly be open to helping.
