### ISSUE TITLE
add unpaid status order in reports

### ISSUE THREAD

**Issue by fmourey** [concrete5-community-store/community_store#389]
Hello,
I have to questions about the report pages.

Is it possible to add the orders with the status 'Unpaid' in the report pages ?
And would it be possible to add a custom report page easily ? Like the products report page but with more informations.

What I'd like to achieve :
I have a website selling concert tickets, with the possibility to pay in cash at the event.
I'd like to have a report page for the event listing all orders with their statuses, payment options, payment status,... so i'd be able to generate a list of all the reservations the day of the concert.

If you could point me in the right direction.

Thank you for your wonderful job !

**Comment by Mesuva** [comment]
From what you've described I think the individual product reports (/dashboard/store/reports/products) have everything you'd need on it _except_ for the payment status. If a column for that was added, would that work for your needs?

In terms of adding custom reports, there's nothing stopping someone from creating any new dashboard functionality, contained within a seperate package and installing the new dashboard pages within the same part of the dashboard. So that's not _easy_ as such, there's no report builder in the shop, but if you are comfortable with making concrete5 packages, you could copy much of the existing report code and develop your own reports separately.

**Comment by fmourey** [comment]
Thank you for your answer !
The individual product reports cover almost all my needs. I'd just need the payment option (cash, bank transfer,...), to show all the transactions for this product (even the unpaid one) with their status (Paid / unpaid), and if possible the price of the transaction. 

I'll look into creating a new package for a new dashboard page. I only made simple packages until now, but it's always a good way to learn (I'm not a professional).

**Comment by Mesuva** [comment]
I've updated the report in this branch here:
https://github.com/concrete5-community-store/community_store/commit/e7523599a1c6a6dc5852b3587bf6df2670194262

It now includes the payment status, the payment method and the price paid for that particular product. 

It's in a seperate branch, but I'll be merging that sometimes soon into the master, so you should be pretty safe to directly apply the changes (also it's in code that doesn't impact the rest of the shop)
