### ISSUE TITLE
Removing Select States from ordering

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#390]
We sell products with Mercury, there are a few certain states that we cannot ship mercury products to. Is there a way to disallow these states during the checkout process?

**Comment by AdamBassett** [comment]
There is not an easy way.  I had a client that needed Alaska and Hawaii removed because of the unpredictable shipping. As a hack way of doing it overrode the ```checkout.php``` file and made a new array of states with those states missing.  This way the states where missing in the drop down in the cart.  Now that does not mean that some one couldn't hack it back in but in that case you could just refund and refuse the order because they hacked the site to do it.  Not the best solution but it worked for my time frame.

**Comment by mdius** [comment]
The only issue, this only applies to selected products. We have like 600 items and this would apply to about 100 right now.

**Comment by AdamBassett** [comment]
That's a tough one.  Carts a generally not that specific.  This is going to require some custom code.

You might be able to group all the products that this applies to and then run some logic to check if one of those products are in the cart. Then limit the state drop down and show a message as to why the state is not listed.

**Comment by mdius** [comment]
Yeah, I figured this. It is beyond my skills, if it becomes more of an issue I'll reach out for a custom upgrade quote.
