### ISSUE TITLE
Missing an assigned ID for field 'attribute_key'

### ISSUE THREAD

**Issue by mhawke** [concrete5-community-store/community_store#392]
I'm on 8.4.2 but it happened on 8.4.0 also. During the Checkout process, after filling in all my personal info and clicking 'Next', the screen just refreshes and the Logs show this:

Exception Occurred: C:\xampp\htdocs\bevc-aug-2018\updates\concrete5-8.4.2\concrete\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php:87 Entity of type Concrete\Core\Entity\Attribute\Value\UserValue is missing an assigned ID for field 'attribute_key'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly. (0)

No clue whatsoever where to start.

**Comment by Mesuva** [comment]
I think this can occur when an attribute is missing - I would check that you have the same attributes for a user set up as they are for an order. Perhaps drop a screenshot here.

Is this with the latest master, or a release?

**Comment by mhawke** [comment]
Yeah, this is probably not good. Duplicate attributes. How?? Who knows.

![image](https://user-images.githubusercontent.com/7385575/45933459-4c6de600-bf5b-11e8-95f8-e0106f868c37.png)

I uninstalled/reinstalled and all is good.

**Comment by GlennMallon** [comment]
This is happening for me also.  I am writing 60 answers for questions and writing it to the user attributes.  When I do, I get this error.

Exception Occurred: /public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:87 Entity of type Concrete\Core\Entity\Attribute\Value\UserValue is missing an assigned ID for field 'attribute_key'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly. (0)

I would have to reinstall concrete to fix this?

**Comment by Mesuva** [comment]
@GlennMallon I thinking this might be more of a concrete5/Doctrine issue, rather than a Community Store one, since saving user attributes is really just handled by concrete5's core, and Community Store doesn't do anything unusual in that regard. Does it happen every time you to try to save, or just sometimes?

**Comment by GlennMallon** [comment]
This happens every time, currently.

**Comment by dimger** [comment]
@Mesuva just in case this is still an issue. I had a similar error message and the problem was that i was creating a new attribute and right after i wanted to update a page's value on that attribute. It seems that if you do this in the same request cycle it throws this error. My solution was to clear caches right after the attribute creation ($this-app->clearCaches(); ).

**Comment by Mesuva** [comment]
@dimger interesting, caching definitely feels part of the problem here.
