### ISSUE TITLE
Syntaxerror after upgrade to 1.4.7

### ISSUE THREAD

**Issue by xb385** [concrete5-community-store/community_store#413]
Hello everyone,
I just upgraded to 1.4.7 and everything seems to work except when i try to add a product to the cart from a detail page. I get the following error: 

Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.n.parseJSON (jquery.js:4)
    at Object.success (communityStore.js?v=1.4.7:122)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at y (jquery.js:4)
    at XMLHttpRequest.c (jquery.js:4)

anyone else got this? a solution would be great! 
thx :)

**Comment by Mesuva** [comment]
Can you share a URL?

Have you hard refreshed your browser, in case you've done a major-ish upgrade and you're still viewing an outdated javascript file?

**Comment by xb385** [comment]
Here you go, thx for checking :) 
http://test.fer-o.be/producten/eettafel-4

**Comment by Mesuva** [comment]
I just took a 8.3.1 concrete5 site, with an older version of community store installed (1.3 something), and upgraded community store to the latest 1.4.7 release. Adding a product to the cart still worked. I also then upgraded concrete5 to 8.4.3 and that still worked.  Both those versions match what you are running, so I'm not immediately thinking there is a bug with the release.

When you add something to the cart I can see it sending the message to the server, but then it comes back as an empty request, instead of returning the response that would tell the javascript to open the cart, etc.  That's what is causing the syntax error, it's simply not getting anything back from the server.  Why that is happening I can't say - perhaps try turning on full debug at /index.php/dashboard/system/environment/debug  and taking a look at the request made to  http://test.fer-o.be/cart/add in Chrome's inspector, to see if any error messages are returned.

(or turn it on and I can take a look)

**Comment by JohntheFish** [comment]
I recently experienced this. Turned out to be my custom block templates did not implement the ccm token which has been added in more recent store versions.

**Comment by Mesuva** [comment]
Ah yes!

![screen shot 2019-01-24 at 4 33 14 pm](https://user-images.githubusercontent.com/1079600/51692925-d30ffe00-1ff5-11e9-97b3-edbf4545c3e7.png)

**Comment by xb385** [comment]
Aha, so i need to review my templates!
I'll get to reviewing and will report back but i'm pretty sure that this will be the issue :)

**Comment by xb385** [comment]
Every single one of you is amazing, it was indeed an issue with a custom block! thanks everyone for the help!, 

issue closed!
