### ISSUE TITLE
Issue with tax class with two rates

### ISSUE THREAD

**Issue by JeffPaetkau** [concrete5-community-store/community_store#443]
I just added a product to my store which requires me to charge both GST and PST in the tax class. However, during checkout the following exception is generated.

`Exception Occurred: /home/concrete/concrete5-8.5.0/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115 An exception occurred while executing 'INSERT INTO CommunityStoreOrderItems (pID, oiProductName, oiSKU, oiPricePaid, oiTax, oiTaxIncluded, oiTaxName, oiQty, oiQtyLabel, oID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [10, "Greenhouse", "", 350, "17.5,24.5", 0, "GST,PST", 1, "", 2455]:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'oiTax' at row 1 (0)`

**Comment by Mesuva** [comment]
I think I know what this is - originally the fields on the CommunityStoreOrderItems table, oiTax and oiTaxIncluded were varchar fields, to be able to handle saving down a comma separated list of taxes. I mistakenly changed them at one point to decimals, but forgot to change them back on this table.

The fix for this is here: https://github.com/concrete5-community-store/community_store/commit/3a5d732931cd7d3135fe82be0a0421b147a121df
You can make that change, then go to /index.php/dashboard/system/environment/entities/view and hit the red 'Refresh Entities' button, and that will change the field types for you.

Or you can just manually change those fields in the database to varchars, that would be safe to do too.
