### ISSUE TITLE
Cart button does not work on product detail page

### ISSUE THREAD

**Issue by Mesign** [concrete5-community-store/community_store#457]
Don't know if this is the right place to ask but when I click the add to cart button (on the product detail page) I only see a loading .gif. (I don't get an error when I am on the product list page and adding to the cart) I get the following error:

**Console error**
`http://xxxx.xx/CMS/index.php/cart/add 500 (Internal Server Error)`

**Log:**
`Exception Occurred: /home/xxxx/domains/xxxx.xx/public_html/CMS/packages/community_store/src/CommunityStore/Cart/Cart.php:152 Call to a member function allowCustomerPrice() on null (0)`

I did upgrade to the latest version. I don't know if I had this problem before the upgrade.

Maarten

**Comment by Mesuva** [comment]
How far back did you upgrade from?
Have you got any custom product block/list templates in place?

**Comment by Mesign** [comment]
I upgraded from 2.0.5. I tested it again with a other page template / and disabled custom block and found out when it doesn't work. 

When I have 1 product block on the page I all works fine, but when I have 2 or more product blocks it doesn't work. 

In my template I have used the product block on 3 places in a template. 1 to show the images, 1 for title, price, small description, add to cart and de last 1 to show the large description.  

So when I delete 2 block it works.

**Comment by Mesuva** [comment]
I'm seeing why this is an issue. When the add-to-cart button is clicked the Javascript looks to find the form for that product on the page, but since you have multiple of the same product on the page it is getting confused and not able to find all the data it needs.

It's quite a tricky one to solve, and looking at the code I'm not seeing a quick fix for this. It's perhaps a case of these product blocks being used in a way that wasn't really anticipated.

Instead, what I would suggest that either:
- create a new product block template that had the layout you need, instead of using multiple blocks on the page
- or, create a new product block template, which can be just a copy of the default one, but remove from line 21 ` id="store-form-add-to-cart-<?= $product->getID(); ?>" `
Then apply that template to all the blocks you have on your page that don't have the add to cart button showing.

**Comment by Mesign** [comment]
Then I will create a custom block template. Thank you!
