### ISSUE TITLE
Product basket events

### ISSUE THREAD

**Issue by agentsquidflaps** [concrete5-community-store/community_store#471]
It would be extremely beneficial to see an 'on_basket_add', 'on_basket_update' and 'on_basket_remove' event

**Comment by markbennett1973** [comment]
I would love to see these events added!

**Comment by Mesuva** [comment]
Adding events shouldn't be too tricky, but deciding what actual 'payload' the event should have is a bit trickier to decide. 

For example, it would need to include the details of the cart (either before or after the change to it), plus the details of the product being added/removed. The format for these are a bit loose, as it's more a piece of database being supplied via the Javascript, some IDs, etc, rather than an object in the database.  

I'll take a look at what can be done so it's flexible.
