### ISSUE TITLE
bulk upload from csv

### ISSUE THREAD

**Issue by skau61** [concrete5-community-store/community_store#491]
Hi, would it be possible to upload all the store from a CSV, and update it periodically using csv ?
Enter files could be a csv and a directory of images with a cross-site relationship to csv
This would give a really effort in using C5 to build shops using other business packages
I'm dealing to build a site for a pharmacy, they do have 1000s of products and things changes every day, so a hand drive site is not confortable

**Comment by Mesuva** [comment]
It should be possible, you can fetch products and make updates to them using the API. Or as the database is pretty simple, it's probably easiest/fastest to just to do direct database updates, based on the SKU. 

I'd be writing it as an automated job, so you can trigger it manually or cue it up for automatic running.

The actual handling of CSVs isn't built in though, as I'd be suggesting it's something that should be built as a seperate add-on, so it can be changed independently. 

Everyone is going to have different CSV formats, different updating rules, different sources of the data, etc, etc, so it's pretty hard to specify just the one process and format. And it might not always be a CSV either, it might be some external database or API - it's likely to be something that someone customises to suit their needs. 

So it's unlikely I'll be adding such directly to the store myself, but what I am happy to do is make any tweaks to the store that _supports_ an import/update process (new database fields if required, for example)

I do have some code around that is in an automated job that fetches files from a remote source and imports them to the file manager, so that is possible too.

**Comment by skau61** [comment]
Yes, sounds great.. I'll take a look on tables just to have a feeling about complexity.
The point that I consider difficult is load bulk images in standard c5 and then link them in shop tables... Did you consider it?

Best regards
Michele from Rome

-------- Messaggio originale --------
Oggetto: Re: [concrete5-community-store/community_store] bulk upload from csv (#491)
Da: Ryan Hewitt
A: concrete5-community-store/community_store
CC: skau61 ,Author


It should be possible, you can fetch products and make updates to them using the API. Or as the database is pretty simple, it's probably easiest/fastest to just to do direct database updates, based on the SKU.

I'd be writing it as an automated job, so you can trigger it manually or cue it up for automatic running.

The actual handling of CSVs isn't built in though, as I'd be suggesting it's something that should be built as a seperate add-on, so it can be changed independently.

Everyone is going to have different CSV formats, different updating rules, different sources of the data, etc, etc, so it's pretty hard to specify just the one process and format. And it might not always be a CSV either, it might be some external database or API - it's likely to be something that someone customises to suit their needs.

So it's unlikely I'll be adding such directly to the store myself, but what I am happy to do is make any tweaks to the store that supports an import/update process (new database fields if required, for example)

I do have some code around that is in an automated job that fetches files from a remote source and imports them to the file manager, so that is possible too.

**Comment by Mesuva** [comment]
I still think for images that there could be different ways to do it, depending on where the images are fetches from - so I'd not being wanting to code something in to handle this. 

As I said before, happy to supply some example code on how this could be done. There are build-in concrete5 functions to make this quite easy.

**Comment by Mesuva** [comment]
Just following up from this one, I recently discovered (or at least was reminded) that this exists: https://github.com/dbuonomo/community-store-import
Even though it's a bit older, I believe it still works fine with version 2 of Community Store
