### ISSUE TITLE
Adding Discount Code Throws a  SQL DriverException error

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#492]
Having a new discount code error. No idea when it started to happen, but when you apply a discount code you get an SQL error.
![Error SQL](https://user-images.githubusercontent.com/28864099/65432783-cee8ea00-dde9-11e9-91e2-604e009529f4.jpg)

Please try this:
https://www.mytinytown.com/products/tilt-switch-1-amp-valox-case-06-inch-leads
Go there add to cart
Check out
Apply "CartDiscount" You don't even have to put in a good code for the error.
Instantly see errors.
I tried to check my PHP from 7.3 to 7.2, 7.0 and 5.6 with no luck.

**Comment by Mesuva** [comment]
This has cropped up because of your database having different settings, rather than something to do with PHP.

It's to do with a setting ONLY_FULL_GROUP_BY, and when that's on queries that use a group by have to be formatted a more specific way.

A quick fix is to disable this setting in the database, you'd need to follow something like this:
https://tableplus.com/blog/2018/08/mysql-how-to-turn-off-only-full-group-by.html

In the meantime, I'll look to adjust this query so it's compatible with newer MySQL/MariaDB settings

**Comment by mdius** [comment]
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

I ran that and now it works. So, did this fix it, or till the next reboot.

Either way, thank you, again, VERY much!!!

**Comment by Mesuva** [comment]
Great!

I've coded up a fix for this, one that cleans up a the code a bit further. Will push up soon once I'm happy with it.

**Comment by Mesuva** [comment]
Turning the ONLY_FULL_GROUP_BY on for my database and taking a general look around concrete5, I'm seeing other issues pop up - so I'd be suggesting that it's still premature to work with it on, and it's best to leave it off like you've done.

I have however pushed up a fix and a rework of the discount handling, good for future compatibility.  https://github.com/concrete5-community-store/community_store/commit/acc6c73140d930bdd94ce0566589a574bae93570
