### ISSUE TITLE
Product List

### ISSUE THREAD

**Issue by TeddyNovak** [concrete5-community-store/community_store#514]
Hi Ryan,
Is there a way of rendering the ‘product list’ block on a product page to look the same as a non product page. I’ve tried modifying/removing code but cannot get the desired result. See screenshots.

![Normal-Product-List](https://user-images.githubusercontent.com/16307511/75475487-c6946c80-5990-11ea-98e3-6de2da9f2075.jpg)

![Product-Page-Product-List](https://user-images.githubusercontent.com/16307511/75475500-cc8a4d80-5990-11ea-8e00-6ecb29429a5c.jpg)

**Comment by Mesuva** [comment]
I think what might be happening is that the two different blocks on the page create an 'image helper' (specific for Community Store), but in a way where the second one is just a reference to the first, so it doesn't create another copy.. and that means it will keep the same settings as the first block that gets created.. i.e. with the product block settings.

In your product list template, try changing
`$communityStoreImageHelper = $app->make('cs/helper/image', ['product_list', null, $legacyThumbProps]);`

To
`$communityStoreImageHelper = new \Concrete\Package\CommunityStore\Src\CommunityStore\Utilities\Image('product_list', null, $legacyThumbProps);`

We might need to actually make that change in the default template, so that we can have things like related products on a product page respect the thumbnail sizing for that block correctly.

**Comment by TeddyNovak** [comment]
Sorry I didn't back sooner. Your code worked, thanks.
