### ISSUE TITLE
Tying to Cancel Free Shipping on Discounted Items

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#518]
I am trying to add a little code to not show the Free Shipping Method of anything in the cart is discounted, not necessarily on sale.

So, I put in the \CommunityStore\Src\CommunityStore\Shipping\Method\Types\FreeShippingShippingMethod.php
`    public function getDiscounts()
    {
	    $discounts = StoreCart::getDiscounts();
        if (!empty($discounts)) {
		    return false;
        } else {
            return true;
        }
    }`

It doesn't seem to be what I need. Is this something simple, or am I biting off more than I can chew?

**Comment by Mesuva** [comment]
Hi there Joe,

I think you are on the right track, but creating a new function like that isn't really going to do anything.

Instead, you would need to adjust the isEligible function - this is the one that does the work to determine whether to actually offer the method or not.

I think you change it to something like this:

   ```
 public function isEligible()
    {
       $discounts = StoreCart::getDiscounts(); if (!empty($discounts))
       
       if (!empty($discounts)) { 
              return false; 
       }

        //three checks - within countries, price range, and weight
        if ($this->isWithinRange()) {
            if ($this->isWithinSelectedCountries()) {
                if ($this->isWithinWeight()) {
                    return true;
                } else {
                    return false;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
```

So it's just adding those few lines to the top of the function.

I'm ignoring the fact here that the code code of the store really shouldn't be edited (in the same way as concrete5's core), because edits will be overwritten if you update the package.
But for a trivial change like this, if you remember you've put it in place I guess it's not hard to keep track off  (and arguably a lot easier than creating a brand new shipping method just for this)

Let me know if that works.

**Comment by mdius** [comment]
That worked perfectly. I have certain items always discounted so I can adjust the % any time, but always wanted them not shipped free. It worked.

My Free shipping does not kick in till I reach $150, so I added regular items, it displaced the free shipping, then I added my 10% off code and free shipping is gone. Just like I wanted.

Thank you so much!!!
