### ISSUE TITLE
Store Discount % Total Not Matching

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#519]
We are doing a 25% off sale. I set it up in the Discount System on the store.
I'll show a few of the setting.
The Percentage: 25.00, Apply to Items in Cart. Then I use Product Groups to tell which items to discount. This all works flawlessly, but when it adds to totals I get, I'll show our actually order we received totals.
https://www.mdius.com/products/high-temp-float-switch-30-foot-225f107c-normally-open-intermediate-angle-skived-cord-ends
Someone bought 9 of these.
Reg Price: 92.99
Sale Price: 69.74
Total for 9: 627.68, this should be 627.66.

So it seems when adding up the items it is adding the actual full percentage off.
So it is doing this.
Reg Price: 92.99
Sale Price: 69.7425
Total: 627.6825

I assume fixing this should be easy, just a simple database change, but I'm posting to make sure that is all and if someone else runs in to this issue I could see a customer not liking the overcharge even if it is only 2 cents or so.

**Comment by mdius** [comment]
Ok, maybe not something simple in the database.

**Comment by Mesuva** [comment]
This reads that there's a step in the discounting that isn't applying rounding when it's perhaps expected.  

At a glance, I think it would be this line here:
https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Discount/DiscountRule.php#L139
It may instead need to be

`return round($applicableTotal - ($this->getPercentage() / 100 * $applicableTotal), 2);`

More broadly speaking, there's going to be a _little_ bit of occasional inaccuracy with rounding throughout the store, as it uses floats instead of integers (cents) to do its internal maths. Something that handles currencies like this really shouldn't be using floats, but it's not something worth reworking everything to address - the rounding I've suggested above might be all that is needed.

**Comment by mdius** [comment]
Yeah, it wouldn't be the end of the world if we couldn't get it fix,but that being said...

So, I have not tested this fully with a purchase, but I added the same items to my cart and the total was $627.68, then I changed the line of code you suggested and it is now $627.66.

So, it appears to have worked! I did not fully check out with this, but I assume if there were to be trouble it wouldn't have worked at all.

Thank you again!
