### ISSUE TITLE
Issue related to fix for #421

### ISSUE THREAD

**Issue by evgk** [concrete5-community-store/community_store#550]
Setting Reply-To header to an address that is different from From makes email receive a low spam score:

https://stackoverflow.com/questions/48308479/mail-tester-com-freemail-in-reply-to-but-not-from

In our case, with the line to set the reply-to, we get the score of 6.5/10, and if I remove the line the score improves to 9/10.
(-2.503 | FREEMAIL_FORGED_REPLYTO | Freemail in Reply-To, but not From - this is the penalty, link  to test: https://www.mail-tester.com/test-mxh6ajp29, link to test with this line commented out: https://www.mail-tester.com/test-u7pmimuvg).

Apparently there is no good, generic fix to it.

The merchant's email is on gmail, and he's complaining that all notification emails go to spam - and it's predictable given the score of 6.5 out of 10. Commenting out the line solves the problem. Could we add a setting to make setting reply-to header optional? If you think that's fine, I'll post a PR.

**Comment by Mesuva** [comment]
I simply wasn't aware of the impact that would have on spam scores, especially since I think concrete5 itself allows it on form submissions.

Yes, a setting to turn this on and off would be important, where I think the initial setting should be off.
If you have a chance to do a PR that would be fantastic.
