### ISSUE TITLE
List mode for product-list block

### ISSUE THREAD

**Issue by evgk** [concrete5-community-store/community_store#553]
It looks like a substantial minority of customers want to have products displayed in list mode, as in here:

https://order.petespig.com/index.php/online-menu/BBQ-Favorites

I have it implemented with a couple of JS hacks right now, but I think the best solution is to have a setting on product list block in Pagination and Display Options section that controls the display mode. Default should be 'grid', and it should be possible to switch it to 'list'. When 'list' mode is selected, it will set the Products per row to '1' and hides that select. As to the layout itself, it can be done with a couple of small fixes, like on the link above - swapping the thumbnail and name, setting float: left on the thumbnail, and adding the 'hr' separator to make it look well.

I can submit a PR for that, let me know if the above would be fine.

**Comment by Mesuva** [comment]
I'm wondering if a new option would be needed here, as an option of 1 in the product per row is effectively saying you want a list anyway.

Or are you saying this would be a _customer_ facing selection, where they can pick what view they want?

**Comment by evgk** [comment]
The option of 1 product per row is the the first thing we tried, it doesn't work, it's not really a list mode - looks very bad, that's why I had to do those fixes that I listed in the comment - add an <hr>, put a float: left to the thumbnail and swap the thumbnail and the name.

**Comment by evgk** [comment]
Magento does have a customer-facing selection, but I'm not sure such feature would be that useful for our case - it's the merchant that decides how it should be displayed, and we have several merchants wanting list mode specifically.

**Comment by Mesuva** [comment]
Cool, I just wanted to check if that's what you meant, since I've seen that recently on a site.

I think this comes down to the theme and any custom styling that might be needed.
By default on Elemental, when it's shown in 1 column it's intentionally boring/simple, the products should display the same as when they are in columns (name, image, price, options, button one after each other). 

The intention then is that if it doesn't display as you want it to, you just override the block template as you done. I think trying to add these kind of adjustments to the already existing template is going to make it too complex.

**Comment by evgk** [comment]
Ya, but we're talking about a very basic feature here that are supported on other systems, and it's not just about a theme - we're using several themes in our solutions, not just elemental, and community store doesn't really require customization per each theme. It seems weird to add the list-mode customization(e.g., hr tag) to ALL themes - the general HTML layout generated for things like product list blocks should not be theme dependent, and that's how it is now, it's working just fine across multiple themes. Adding the ability to generate HTML layout that is compatible with list mode as a part of standard functionality seems much more reasonable - it wouldn't be the case if it wasn't something that a lot of customers seem to be expecting.

**Comment by evgk** [comment]
> By default on Elemental, when it's shown in 1 column it's intentionally boring/simple, the products should display the same as when they are in columns (name, image, price, options, button one after each other).

Yes, and it's exactly the case for other themes, but that's not really a list mode.

**Comment by Mesuva** [comment]
I feel like I'm still not understanding what you are saying is missing here.

What makes it a list mode exactly?  Is there a common HTML output, in bootstrap, that you'd be expecting to see?
Is it that the image isn't floated to the left of the title and details?

**Comment by evgk** [comment]
Two things:
1. No HR tag to separate the entries - list mode is clearly better with it
2. Thumbnail and name should be swapped, and float: left should be applied to thumbnail, since it makes much more sense to display the name to the right of the image in list mode, unlike the grid mode.

**Comment by Mesuva** [comment]
I understand and agree that a list mode for the block would be useful (even to help control custom templates).

The bit I'm not sure about is the use of hr tags, or floating the image to create that layout. 
Maybe that makes the most sense, but I'm just wondering if there's a bootstrap layout that is going to be a bit more.. bootstrappy.. for example, instead of floating the image, should it and the contents be put into some bootstrap columns. 

So to answer your original question, I think adding the option to the block would be great, and a PR would certainly be welcome. It's really just the finer details of the actual output for a 'list' that we might need to play around with.  (but it might also just be exactly as you've suggested!)

**Comment by evgk** [comment]
I used Bootstrap layout to place the image - but there is no bootstrap-specific way to do horizontal separators, so hr tag is an adequate way to solve it.
