### ISSUE TITLE
Cannot add Additional Images Since Upgrade to Concrete 8.5.4

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#596]
Concrete Version 8.5.4
Community Store Version 1.4.7
I cannot add additional images, I used to just click them and it would select them. This no longer happens. Cleared my cache with no help. There is no error message.

**Comment by Mesuva** [comment]
This was something fixed in version 2.x of Community Store, but you should be able to manually apply the same change to version 1. You just have to find and remove this line:
https://github.com/concrete5-community-store/community_store/commit/e7c426adb7ea7fee2b529095594184115d290ded
from single_pages/dashboard/store/products.php

**Comment by mdius** [comment]
Perfect!
Thank you again.
