### ISSUE TITLE
Option list required

### ISSUE THREAD

**Issue by Vidall** [concrete5-community-store/community_store#599]
Hi There,

I am currently building a site with C5CS and love it so far, it's very flexible, and a delight to use, I have come across what I think is a bug, but it could easily be that I am expecting the wrong outcome.

When adding a product variation, using the "Option list" there is a setting to make the list "required", in my mind, when this is checked, you shouldn't be able to add the product to the cart unless you have selected a variation, in reality, the product gets added to the cart and the first variation is added by default if nothing is selected.

Is this a bug, or am I misunderstanding what this is for? thanks in advance.

**Comment by Mesuva** [comment]
You might have hit a bug. There's been a bit of work on the option drop downs lately, which will make it's way into a new release which is due, but this particular issue I'm not 100% sure about.

When you say 'unless you have selected a variation', what is showing on the dropdowns on your product when they are first displayed?  If you are using the options in a variation, it really should be set to required regardless of the required setting, but I'm a little confused by what you've described as the dropdowns shouldn't allow nothing/blank to be selected...

Would you be able to attach a screenshot or two explaining what you are seeing?  

Also, thanks for the nice feedback, I'm glad you're finding the add-on flexible!

**Comment by Vidall** [comment]
Hi @Mesuva,

Thanks for the speedy response. 

I have included a screenshot to show what is going on (please ignore the design the site is far from finished) can I  just walk you through what I was expecting to happen, as I don't think I explained it very well before:

1/ Land on a product page, click on "Add to cart"
2/ There would be some kind of error message saying "Please select a variation before a product is added to your cart" as the variation is required.
3/ Said item is added to cart

What is currently happening:

1/ Land on page and click "Add to cart"
2/ First variation in the option list gets added to cart

Could be that my expectation is just different to the actual function of "required", in my head the first scenario is what I pictured it to do.

![Screenshot_2021-01-28_at_11_46_01](https://user-images.githubusercontent.com/1519760/106135957-7e616980-6160-11eb-96aa-d818a0a6fc44.png)

**Comment by Mesuva** [comment]
I'm understanding - yes I think it's just different behaviour to what you might be expecting/wanting.

By default a product will always show you the first available variation. The main reason why is that is so that it can display the an actual price and image for a variation, as without having a variation initially selected it's a bit unknown what details to show.

I guess it could show the base rate and product image instead...  but it can come down a little to the type of product, whether it makes sense or not.

I'm soon to review a new PR for Community Store, when I do that I'll take a look to see if this could be adjusted based on the required option.

In your example though, are you using actual variations to control things, or could you just use the price adjustment field for the options?  I ask, because if you are _only_ adjusting the price or weight using the drop downs, using variations isn't necessary.

**Comment by Vidall** [comment]
Yep, that makes sense re having a base price/image to show, I can see how that would be an issue otherwise.

I have tried using the price adjustment, as well as a variation, but both seem to behave in the same way? or am I missing a difference?

**Comment by Mesuva** [comment]
They achieve the same result with the pricing, it's really just that it's easier to set up and manage price adjustments compared to variations. In your case that's not a big factor as you've only got the one option in place, but when you've got many options in place that need to adjust the price you can end up with too many variations.

I only suggest using variations when you actually need to use them (i.e. you are changing the product image, the SKU, or needing to manage specific stock levels). In your particular example I'd really just use the price adjustments since it looks like you're only adjusting the price.

**Comment by Vidall** [comment]
No worries, I will probably just use the price adjustments then, sounds easier to manage.

I think what I will end up doing is just hide the add to cart button until a variation has been selected, then there is no danger of an item ending up in the cart without the appropriate option added to it, I get that what I am doing is a bit of an edge case, I really appreciate your help though.
