### ISSUE TITLE
Checkout just spinning again, but this time not going from Billing to Shipping Details

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#612]
Checkout is just spinning, all was working good yesterday. Nothing edited or changed over night.

www.mdius.com

Just add anything to the cart and see. I tried clearing the cache a couple times.

**Comment by Mesuva** [comment]
Your site isn't coming up for me at all. Server down or overload maybe?

**Comment by mdius** [comment]
Try it again?

**Comment by Mesuva** [comment]
It's back up now.

Adding to the cart is working for me, it just took several seconds for it to complete.
No errors as such, just a long time for the server to respond.

I'm thinking your server is under heavy load or similar.

![Screen Shot 2021-05-04 at 4 12 02 pm](https://user-images.githubusercontent.com/1079600/117026291-91518000-acf3-11eb-99de-e95d64472031.png)

**Comment by mdius** [comment]
Ok, I am going to contact the server. Thank you

**Comment by mdius** [comment]
Well I think I know what my trouble with EasyPost is.
`protected $pkgHandle = 'community_store_easypost';
protected $appVersionRequired = '8.0';
protected $pkgVersion = '2.1';`
When I installed this I wasn't thinking that I am using the older version of Community Store.
Could this be most of my issue I've been having?

**Comment by Mesuva** [comment]
I actually don't think that would make much of a difference.
I developed that add-on during the earlier days of Community Store, and I don't recall having to change it for version 2 of Community Store.  I think you'd see quite specific errors displayed if there was some kind of conflict.

On the site now, I'm able to add items to the cart, progress through the checkout and have Easypost return some shipping prices, and proceed to the payment options. So that all looks fine to me.

The thing to keep in mind is that Easypost is quite fussy with addresses, you have to put in real ones that can be recognised, and occasionally it can refuse to recognise an address because of how it's been entered.

![Screen Shot 2021-05-04 at 7 20 34 pm](https://user-images.githubusercontent.com/1079600/117050912-d7b3d880-ad0d-11eb-9ca8-345d167dd0f3.png)

The earlier issues I saw all looked to be server performance related.

**Comment by mdius** [comment]
Awesome, if you don't think I need to worry about it, I won't. I just notice from time to time I have issues with my shipping.
But yeah I contact the server host and they definitely said there was something going on and they are looking in to it. Seems like they fixed it so far, still a little slower, but nothing like it was.
Thank you again for your help.
