### ISSUE TITLE
completeOrder of Order class requires session

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#63]
The function that finalises the order after a successful transaction relies on the session to find details about the order to complete. 

If the order either creates a new user, or someone is already logged in, this will not update all details on the user correctly when an external payment method is used (i.e. Paypal).

So this needs to be refactored so it can be triggered from any source and session info is not required.

**Comment by Mesuva** [comment]
I've marked this as a bug, as I don't believe Paypal (or similar functioning gateways) will work correctly until this is resolved.

**Comment by Jozzeh** [comment]
I think the issue is 2 fold:  
1. What if a person cancels on the payment gateway 
2. The webhook from the online payment gateway does not contain the session

Problem 1 has an easy fix : Add a cancelled page below the checkout.
Problem 2 is a bit more tricky...  
The problem resides in the session not being available in the webhook, which is to be expected since the payment gateway (for example the paypal server) does not have the order session.  
Solution: Check the payment not on the webhook, but on the returnURL.
- On the notifyURL the transactionID is set on the order but not completed and not marked as paid. 
- register a route to a custom method in the payment gateway class (on_start method in the controller.php) .
- The returnURL goes to the newly registered route. 
- Customer returns after completion to the returnURL -> order session is available again. 
- Because the transactionID was saved on the notifyURL we can ask the payment gateway, what the status is of the transaction with that ID.
- - if paid -> completeOrder and mark as paid -> redirect to checkout/complete
- - if open (not paid, not cancelled) -> completeOrder and mark is unpaid -> redirect to checkout/complete
- - if cancelled -> redirect to checkout/cancelled

I'm not familiar with the paypal API so I'm not sure this will apply to paypal...  This does work on a different online payment method I am currently working on (and hopefully be releasing soon).

**Comment by Jozzeh** [comment]
My working example may take some time ... I forked the paypal payment gateway to my repositories and made the changes I described above. However, the call to paypal to check the payment status has not been implemented. [Click here to see the forked repo](https://github.com/Jozzeh/community_store_paypal_standard)

Note: this is theoretical, I have no idea if it will work. On the other hand, going from session to something else is a huge change.

**Comment by Mesuva** [comment]
Thanks @Jozzeh, I think you make a really good point about a cancelled transactions, we're probably missing a screen to handle that sort of scenario.

With handling the check of payment on the returnURL, I see that as a potential problem as there's no guarantee that the customer won't just close their paypal window (or whatever external gateway), immediately after they've made their payment. In that case you've got a transaction that has happened but an order that hasn't been marked as paid. 

On the other hand the webhook back to the site is considered to "always" occur, something that is going to ensure that the order is marked as paid. This passes through the order id, so I think this method is going to going to be fine.

What this issue specifically refers to is that as part of the order completion process it's still looking at _some_ details from the session, to make updates to the related user.  I've got a feeling the Paypal add-on for community store does actually work correctly, it's just that you can't use it to create new user accounts or update user groups.

**Comment by Jozzeh** [comment]
@Mesuva You are completely correct about the webhook. It should always occur.  
I do think the webhook (with the current implementation), should only be used for marking as paid and not to complete an order. 

Paypal will indeed work , but a lot of things will not fire without the session. For example:  
- Order Emails won't be send 
- Cart won't be cleared
- Unsetting the shipping type 
- Create new user account/update user groups (as you've mentoined)  

By not having the above, an online shopper will be left confused about what happened with his/her order and payment.

A more robust solution is necessairy. So your first proposition when starting this issue (refactoring/rethinking) seems the best option. 

A fairly easy fix could be to save the customer details in the database and linking it with a certain order when the payment starts. (Sort of like drafts but for customers instead op pages)

**Comment by Mesuva** [comment]
@Jozzeh I'm seeing what you mean here. I think we could use the webhook to trigger off the final process of the order completing, which will send emails and adjust user groups, but you're right in that the session is needed to clear the cart, unset the shipping type and log in the new user account.

I think we could start off by adjusting the order completion step to use as little as possible from the session, then we could split off the session related stuff to a different function/process.

Something to do with a good chuck of spare time and a strong coffee!

**Comment by Jozzeh** [comment]
After looking into this , I think I have found a way. Just like you said, splitting off the session related stuff to a different function/process.   
I've noticed the orderComplete function now uses no session except for : 
- Discount Code clear
- community_store.smID
- Cart clear  

I've written a new payment gateway (still in test, Mollie payment gateway) but I've solved the issue by registering an extra route in the controller.php of the package. So I have 2 routes registered in the controller.php ... one for the webhook and one for the returnUrl.  

```PHP
public function registerRoutes(){
    Route::register('/checkout/mollieresponse', '\Concrete\Package\CommunityStoreMollie\Src\CommunityStore\Payment\Methods\Mollie\MolliePaymentMethod::validateCompletion');
    Route::register('/checkout/ordercompletion/{oID}', '\Concrete\Package\CommunityStoreMollie\Src\CommunityStore\Payment\Methods\Mollie\MolliePaymentMethod::customerValidation', 'customervalidate' ,array('oID' => '\d+'));
}
```

```PHP
public static function customerValidation($oID){
   //Sends customers to this function when the transaction is completed or cancelled
   //this function checks if the payment was successfull or not using the $oID to get the order
   //depending on the payment status , the user will be redirected to the appropriate page
}
```

This returnUrl route goes to a function in the payment method and actually has the order ID as a parameter in the Url.  
In this function, I first check if the payment was successfull/paid (getting the transaction ID from the order).  
If successfull -> clear the session stuff and redirect the user to /checkout/complete .  
If cancelled or not paid -> redirect to /cart

I will try to upload the new payment gateway as soon as possible.  
If paypal has the ability to check a payment status outside of the webhook, this might solve the issue.  Even though we are not sure a user will actually return to the webshop after the payment, the user will get an e-mail with the order details (because the orderComplete function is done in the webhook) .

**Comment by Mesuva** [comment]
@Jozzeh I've reworked the order process here: https://github.com/concrete5-community-store/community_store/commit/4fcecbca545f26aa9b10d0fedecf6375739d7294

It needs to be tested further, but I believe I've split out the order process so that it doesn't require session data at all to complete. It also means that we should be able to add a 'resend invoice' function to the dashboard. 

Will test this further, but you're welcome to have a look at my changes so far

**Comment by Jozzeh** [comment]
I've had a quick look at the changes and it looks excellent.  
Will test it as soon as possible. 

The resend invoice might be a good enhancement to the dashboard, in case an invoice mail is lost.

**Comment by Mesuva** [comment]
I've finished this up and merged it, including a resend invoice function.

I've tested this with Stripe, Paypal and Pin Payment gateways, as well as the Invoice payment, for normal and membership products, logged in and logged out. All seemed correct to me.

The recent change also means that if someone puts through an invoice order for a membership product, they wont get their login immediately, but when the order is marked as paid by an admin it will complete the rest of the process (new user account, membership groups)
