### ISSUE TITLE
Taxes and discounts

### ISSUE THREAD

**Issue by rii-J** [concrete5-community-store/community_store#74]
If a discount is applied to a product, the taxes are still calculated from the original sales price, i guess this is wrong as the sales tax applies to the price after the discount is applied. In only few exceptions the taxes are applied to the original price ( Manufacturer or distributor vouchers where seller is reimbursed )

**Comment by Mesuva** [comment]
This is certainly an issue and something that was overlooked. The way it calculates the totals needs to be reworked. 

It's pretty tricky - I'm tempted to disable discounts for the time being until this can be addressed.

**Comment by rii-J** [comment]
for the percentage discounts should be easy to fix, but i´m still uncertain how to calculate taxes when the discount is an amount and there is more than one product in the cart with different taxes! how should the discount be applied?

**Comment by Mesuva** [comment]
What I've worked out is that it's about calculating a percentage difference between the non discounted totals and the new totals, so I don't think it makes much difference whether it's a fixed amount or a percentage off. Once this percentage is worked out, it's then a case of determining where to reduce the tax amounts. That gets really complex quickly, as there are both inclusive and exclusive tax options, as well as cases where taxes can be applied to shipping or not.

From looking at the code so far I've realised that the getTaxes function of CommunityStore\Tax\Tax needs to return not just a tax total, but separate tax values for _both_ the products and shipping.
Then I think the getTotals function of CommunityStore\Utilities\Calculator would be able to work out whether it needs to reduce the tax for the shipping component, or the product component or both.

(i've also worked out getDiscountTotals doesn't get used so it should be removed)

**Comment by rii-J** [comment]
not sure if i undestood, i would do it that way:
P is Product so P1 with the price of $100 (taxes 10%)and P2 with $300$ (Taxes 20%)  and a discount amount of $20, so the taxes should be calculated with the percentage from the subtotal:
25% for P1 and 75% for P2, right?

**Comment by Mesuva** [comment]
I've heavily reworked the way taxes are calculated, getting them to update when discounts are applied in this branch here: https://github.com/concrete5-community-store/community_store/tree/tax-discount-rework

I also discovered quite a serious existing bug which I've already fixed in master.

I was also able to reduce the number of ajax calls in the checkout as a positive site-effect from this work. I also removed quite a few functions that really just duplicated functionality.

I _removed_ from the discounts the ability to take the discount off of the grand total.
On the surface it would seem like an easy one to implement, but it actually proves very difficult to then work out where you need to adjust the taxes. Having it as either subtotal or shipping discounts makes it very clear as to what you are actually discounting.

If you (or anyone else reading this) has the opportunity, it would be great if you could have a test/play with this branch, to see if there's any particular scenarios I've missed testing myself.

There are quite a few combos to test - inclusive/exclusive taxes, whether taxes apply to shipping or not, multiple taxes in play, discounts that impact either the subtotal or the shipping.

**Comment by rii-J** [comment]
alright, we´ll test it tomorrow.

**Comment by rii-J** [comment]
so i tested all scenarios and the taxes are calculated right, i just found an other bug in the discounts, even if you enter a perecentage value without making in it as a single use code, the checkbox for single use code is always checked!

**Comment by rii-J** [comment]
by the way shipping methods should also have a tax amount!

**Comment by Mesuva** [comment]
I'll check out the bug with the percentages and single use shortly. I pushed up a further lots of changes/fixes after your test.

With the shipping and tax, there is an option on the tax configurations themselves whether the taxes are applied to the items and the shipping, or just the items.

**Comment by Mesuva** [comment]
Fix for the bug with single use checkbox has been pushed up to this branch

**Comment by Mesuva** [comment]
I've merged the tax/discounts fixes, plus some other discounts related tweaks into the master branch.
So I'll close this for now, but please open another issue if you find any issues
