### ISSUE TITLE
Usability Suggestion For Stock Amounts

### ISSUE THREAD

**Issue by ob7** [concrete5-community-store/community_store#77]
What if by default the item was unlimited quantity, but if someone manually enters quantity then it no longer is unlimited?

**Comment by Mesuva** [comment]
You're referring to the variation quantities?

My thinking here was that when you have a product with variations, you're going to be more likely to be managing stock levels, than offering them as unlimited. 

So I thought it was safer to set the initial available to zero, then having all the new options created instantly available as unlimited. Otherwise you could have a period of time where a live product is offering stock for items that you don't have. You'd have to quickly go in and update all the values - safer to not offer items and turn them on.
